In [1]:
pip install icecream

Requirement already satisfied: icecream in c:\users\hiseh\downloads\mta_swipe\venv\lib\site-packages (2.1.2)
Requirement already satisfied: colorama>=0.3.9 in c:\users\hiseh\downloads\mta_swipe\venv\lib\site-packages (from icecream) (0.4.5)
Requirement already satisfied: executing>=0.3.1 in c:\users\hiseh\downloads\mta_swipe\venv\lib\site-packages (from icecream) (0.8.3)
Requirement already satisfied: asttokens>=2.0.1 in c:\users\hiseh\downloads\mta_swipe\venv\lib\site-packages (from icecream) (2.0.5)
Requirement already satisfied: pygments>=2.2.0 in c:\users\hiseh\downloads\mta_swipe\venv\lib\site-packages (from icecream) (2.12.0)
Requirement already satisfied: six in c:\users\hiseh\downloads\mta_swipe\venv\lib\site-packages (from asttokens>=2.0.1->icecream) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.3.1; however, version 22.1.2 is available.
You should consider upgrading via the 'C:\Users\hiseh\Downloads\MTA_Swipe\venv\Scripts\python.exe -m pip install --upgrade pip' command.

In [2]:
from bs4 import BeautifulSoup
import requests
import time
from random import randrange
from icecream import ic
import itertools
import wget

In [3]:
## Requesting web content

url = "http://web.mta.info/developers/fare.html"
response = requests.get(url)

In [4]:
## we add name of our file
soup = BeautifulSoup (response.text, "html.parser")

In [5]:
##targeting the div tag with the class "span-19 last" with the find

holder = soup.find("div", class_="span-19 last").find_all("a")

In [6]:
type(holder)

bs4.element.ResultSet

In [7]:
##adding base_url
base_url = "http://web.mta.info/developers/"

In [8]:
#adding the hrefs to the base_url

all_swipes = [base_url + item.get("href") for item in holder]

In [9]:
##withdrawing the wanted url links into a new list
swipes = ['http://web.mta.info/developers/data/nyct/fares/fares_220507.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_220430.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_220423.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_220416.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_220409.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_220402.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_220326.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_220319.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_220312.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_220305.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_220226.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_220219.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_220212.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_220205.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_220129.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_220122.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_220115.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_210508.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_210501.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_210424.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_210417.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_210410.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_210403.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_210327.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_210320.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_210313.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_210306.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_210227.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_210220.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_210213.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_210206.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_210130.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_210123.csv',
 'http://web.mta.info/developers/data/nyct/fares/fares_210116.csv']

In [10]:
len(swipes)

34

##downloading all the wanted urls in the newlist

link_number = len(swipes)
link_count = 1

for swipe in swipes:
    ic(swipe)
    print (f"Downloaded {link_count} of {link_number}")
    link_count += 1

##downloading

    wget.download(swipe)
#snoozing and telling me for how long before the next downloads
    mysnoozerbug = randrange (2,15)
    print (f"Snoozing for {mysnoozerbug} seconds before next link")
    time.sleep(2)

In [1]:

import os ## for file/folder management
from pathlib import Path ## to provide a path to files/folders
## import the glob library for collecting specific files into a list
import glob
import fileinput
import pandas as pd ## to export csv file

In [3]:
os.listdir()

['turnstile_220305.txt',
 'turnstile_210403.txt',
 'turnstile_210417.txt',
 'fares_220507.csv',
 'MTA_Turnstile2.ipynb copy',
 'turnstile_210206.txt',
 'turnstile_220312.txt',
 'fares_210410.csv',
 'fares_220129.csv',
 'turnstile_210213.txt',
 'fares_220115.csv',
 'swipe_data.ipynb',
 'turnstile_220115.txt',
 'fares_210213.csv',
 'turnstile_220129.txt',
 '.DS_Store',
 'turnstile_210410.txt',
 'fares_210206.csv',
 'fares_220312.csv',
 'MTA_Turnstile2.ipynb.zip',
 'fares_210417.csv',
 'fares_210403.csv',
 'turnstile_data-Copy1.ipynb',
 'fares_220305.csv',
 'turnstile_210306.txt',
 'turnstile_220212.txt',
 'turnstile_210313.txt',
 'turnstile_210501.txt',
 'MTA_Turnstile.ipynb',
 'former txts',
 'MTA_Turnstile2.ipynb',
 'turnstile_220205.txt',
 'fares_210116.csv',
 'turnstile_220416.txt',
 'turnstile_220402.txt',
 'fares_220402.csv',
 'fares_220416.csv',
 'MTA_Turnstile2.ipynb copy.zip',
 'turnstile_210116.txt',
 'fares_220205.csv',
 'fares_210501.csv',
 'MTA_Swipe.ipynb',
 'fares_210313.csv',
 'fares_210306.csv',
 'fares_220212.csv',
 'turnstile_220409.txt',
 'turnstile_210327.txt',
 'turnstile_data.zip',
 'turnstile_210130.txt',
 'turnstile_220226.txt',
 'MTA_Turnstile-Copy1.ipynb',
 'fares_220430.csv',
 'fares_210320.csv',
 'fares_210123.csv',
 'turnstile_220219.txt',
 'turnstile_220423.txt',
 'fares_220423.csv',
 'fares_220219.csv',
 'turnstile_210123.txt',
 'turnstile_210320.txt',
 'fares_210508.csv',
 'turnstile_220430.txt',
 'fares_210130.csv',
 'fares_220226.csv',
 'fares_210327.csv',
 'turnstile_210109.txt',
 'fares_220409.csv',
 'fares_210220.csv',
 'fares_220122.csv',
 '.ipynb_checkpoints',
 'MTA_Swipe-Copy1.ipynb',
 'turnstile_220319.txt',
 'turnstile_210227.txt',
 'fares_210424.csv',
 '2turnstile_data.ipynb',
 'turnstile_220326.txt',
 'fares_220326.csv',
 'turnstile_220108.txt',
 'turnstile_210424.txt',
 'fares_210227.csv',
 'fares_220319.csv',
 'turnstile_data.ipynb',
 'turnstile_210220.txt',
 'turnstile_220122.txt']

In [2]:
## let's capture the files in a list
csv_files = sorted(glob.glob("*.csv"))
csv_files

['fares_210116.csv',
 'fares_210123.csv',
 'fares_210130.csv',
 'fares_210206.csv',
 'fares_210213.csv',
 'fares_210220.csv',
 'fares_210227.csv',
 'fares_210306.csv',
 'fares_210313.csv',
 'fares_210320.csv',
 'fares_210327.csv',
 'fares_210403.csv',
 'fares_210410.csv',
 'fares_210417.csv',
 'fares_210424.csv',
 'fares_210501.csv',
 'fares_210508.csv',
 'fares_220115.csv',
 'fares_220122.csv',
 'fares_220129.csv',
 'fares_220205.csv',
 'fares_220212.csv',
 'fares_220219.csv',
 'fares_220226.csv',
 'fares_220305.csv',
 'fares_220312.csv',
 'fares_220319.csv',
 'fares_220326.csv',
 'fares_220402.csv',
 'fares_220409.csv',
 'fares_220416.csv',
 'fares_220423.csv',
 'fares_220430.csv',
 'fares_220507.csv']

In [3]:
## let's capture the 2021 files in a list
csv21_files = sorted(glob.glob("fares_21*.csv"))
csv21_files

['fares_210116.csv',
 'fares_210123.csv',
 'fares_210130.csv',
 'fares_210206.csv',
 'fares_210213.csv',
 'fares_210220.csv',
 'fares_210227.csv',
 'fares_210306.csv',
 'fares_210313.csv',
 'fares_210320.csv',
 'fares_210327.csv',
 'fares_210403.csv',
 'fares_210410.csv',
 'fares_210417.csv',
 'fares_210424.csv',
 'fares_210501.csv',
 'fares_210508.csv']

In [6]:
## let's capture the 2022 files in a list
csv22_files = sorted(glob.glob("fares_22*.csv"))
csv22_files

['fares_220115.csv',
 'fares_220122.csv',
 'fares_220129.csv',
 'fares_220205.csv',
 'fares_220212.csv',
 'fares_220219.csv',
 'fares_220226.csv',
 'fares_220305.csv',
 'fares_220312.csv',
 'fares_220319.csv',
 'fares_220326.csv',
 'fares_220402.csv',
 'fares_220409.csv',
 'fares_220416.csv',
 'fares_220423.csv',
 'fares_220430.csv',
 'fares_220507.csv']

In [17]:
#getting the categories in the csvs
line_one = "     ,FARECARD"
line_two = "REMOTE, STATION,FF,SEN/DIS, 7-D AFAS UNL,30-D AFAS/RMF UNL,JOINT RR TKT,7-D UNL,30-D UNL,7D-XBUS PASS,TCMC,RF 2 TRIP,RR UNL NO TRADE,TCMC ANNUAL MC,MR EZPAY EXP,MR EZPAY UNL,PATH 2-T,AIRTRAIN FF,AIRTRAIN 30-D,AIRTRAIN 10-T,AIRTRAIN MTHLY,STUDENTS,NICE 2-T,CUNY-120,CUNY-60,FF VALUE,FF 7-DAY,FF 30-DAY"
data_dict21 = {
    "month": [],
    "station": [],
    "full_fare": [],
    "senior_discount": [],
    "seven_day_ADA": [],
    "thirty_day_ADA": [],
    "joint_rail_ticket": [],
    "seven_day_unlimited": [],
    "thirty_day_unlimited": [],
    "seven_day_expbus_pass": [],
    "transit_check": [],
    "reduced_fare_twotrip": [],
    "railroad_unlimited": [],
    "transit_check_annual": [],
    "mailnride_ezpay_exp": [],
    "mailnride_ezpay_unl": [],
    "path_2trip": [],
    "airtrain_fullfare": [],
    "airtrain_30day": [],
    "airtrain_10trip": [],
    "airtrain_monthly": [],
    "student": [],
    "Nice_2trip": [],
    "cuny_120d": [],
    "cuny_60d": [],
    "full_farevalue": [],
    "full_fare7d": [],
    "full_fare30d": []
}

##grouping the 2021 data by months
grouped_data_by_month = {
    "january": data_dict21,
    "february": data_dict21,
    "march": data_dict21,
    "april": data_dict21
}
month = ""

for line in fileinput.input(csv_files):
    if line.startswith(line_one) or line.startswith(line_two):
        continue
    if len(line.split(",")) == 26:
        date_range = line.split(",")[1]
        month_number = int(date_range.split("-")[0].split("/")[0])
        if month_number == 1:
            month = "january"
        elif month_number == 2:
            month = "february"
        elif month_number == 3:
            month = "march"
        elif month_number == 4:
            month = "april"
        continue
    data = line.split(",")
    grouped_data_by_month[month]["station"].append(data[1])
    grouped_data_by_month[month]["full_fare"].append(data[2])
    grouped_data_by_month[month]["senior_discount"].append(data[3])
    grouped_data_by_month[month]["seven_day_ADA"].append(data[4])
    grouped_data_by_month[month]["thirty_day_ADA"].append(data[5])
    grouped_data_by_month[month]["joint_rail_ticket"].append(data[6])
    grouped_data_by_month[month]["seven_day_unlimited"].append(data[7])
    grouped_data_by_month[month]["thirty_day_unlimited"].append(data[8])
    grouped_data_by_month[month]["seven_day_expbus_pass"].append(data[9])
    grouped_data_by_month[month]["transit_check"].append(data[10])
    grouped_data_by_month[month]["reduced_fare_twotrip"].append(data[11])
    grouped_data_by_month[month]["railroad_unlimited"].append(data[12])
    grouped_data_by_month[month]["transit_check_annual"].append(data[13])
    grouped_data_by_month[month]["mailnride_ezpay_exp"].append(data[14])
    grouped_data_by_month[month]["mailnride_ezpay_unl"].append(data[15])
    grouped_data_by_month[month]["path_2trip"].append(data[16])
    grouped_data_by_month[month]["airtrain_fullfare"].append(data[17])
    grouped_data_by_month[month]["airtrain_30day"].append(data[18])
    grouped_data_by_month[month]["airtrain_10trip"].append(data[19])
    grouped_data_by_month[month]["airtrain_monthly"].append(data[20])
    grouped_data_by_month[month]["student"].append(data[21])
    grouped_data_by_month[month]["Nice_2trip"].append(data[22])
    grouped_data_by_month[month]["cuny_120d"].append(data[23])
    grouped_data_by_month[month]["cuny_60d"].append(data[24])
    grouped_data_by_month[month]["full_farevalue"].append(data[25])
    grouped_data_by_month[month]["full_fare7d"].append(data[26])
    grouped_data_by_month[month]["full_fare30d"].append(data[27])

In [20]:
##puttting our grouped monthly data in a data dicttionary
for line in fileinput.input(csv21_files):
    if line.startswith(line_one) or line.startswith(line_two):
        continue
    if len(line.split(",")) == 26:
        date_range = line.split(",")[1]
        month_number = int(date_range.split("-")[0].split("/")[0])
        if month_number == 1:
            month = "january"
        elif month_number == 2:
            month = "february"
        elif month_number == 3:
            month = "march"
        elif month_number == 4:
            month = "april"
        continue
    data = line.split(",")
    data_dict21["station"].append(data[1])
    data_dict21["full_fare"].append(int(data[2]))
    data_dict21["senior_discount"].append(int(data[3]))
    data_dict21["seven_day_ADA"].append(int(data[4]))
    data_dict21["thirty_day_ADA"].append(int(data[5]))
    data_dict21["joint_rail_ticket"].append(int(data[6]))
    data_dict21["seven_day_unlimited"].append(int(data[7]))
    data_dict21["thirty_day_unlimited"].append(int(data[8]))
    data_dict21["seven_day_expbus_pass"].append(int(data[9]))
    data_dict21["transit_check"].append(int(data[10]))
    data_dict21["reduced_fare_twotrip"].append(int(data[11]))
    data_dict21["railroad_unlimited"].append(int(data[12]))
    data_dict21["transit_check_annual"].append(int(data[13]))
    data_dict21["mailnride_ezpay_exp"].append(int(data[14]))
    data_dict21["mailnride_ezpay_unl"].append(int(data[15]))
    data_dict21["path_2trip"].append(int(data[16]))
    data_dict21["airtrain_fullfare"].append(int(data[17]))
    data_dict21["airtrain_30day"].append(int(data[18]))
    data_dict21["airtrain_10trip"].append(int(data[19]))
    data_dict21["airtrain_monthly"].append(int(data[20]))
    data_dict21["student"].append(int(data[21]))
    data_dict21["Nice_2trip"].append(int(data[22]))
    data_dict21["cuny_120d"].append(int(data[23]))
    data_dict21["cuny_60d"].append(int(data[24]))
    data_dict21["full_farevalue"].append(int(data[25]))
    data_dict21["full_fare7d"].append(int(data[26]))
    data_dict21["full_fare30d"].append(int(data[27]))
    data_dict21["month"].append(month)

In [2]:
##zipping the data dict intto a dataframe
data_frame21 = pd.DataFrame(data_dict21)
data_frame21["full_fare"] = pd.to_numeric(data_frame21["full_fare"])
data_frame21["senior_discount"] = pd.to_numeric(data_frame21["senior_discount"])
data_frame21["seven_day_ADA"] = pd.to_numeric(data_frame21["seven_day_ADA"])
data_frame21["thirty_day_ADA"] = pd.to_numeric(data_frame21["thirty_day_ADA"])
data_frame21["joint_rail_ticket"] = pd.to_numeric(data_frame21["joint_rail_ticket"])
data_frame21["seven_day_unlimited"] = pd.to_numeric(data_frame21["seven_day_unlimited"])
data_frame21["thirty_day_unlimited"] = pd.to_numeric(data_frame21["thirty_day_unlimited"])
data_frame21["seven_day_expbus_pass"] = pd.to_numeric(data_frame21["seven_day_expbus_pass"])
data_frame21["transit_check"] = pd.to_numeric(data_frame21["transit_check"])
data_frame21["reduced_fare_twotrip"] = pd.to_numeric(data_frame21["reduced_fare_twotrip"])
data_frame21["railroad_unlimited"] = pd.to_numeric(data_frame21["railroad_unlimited"])
data_frame21["transit_check_annual"] = pd.to_numeric(data_frame21["transit_check_annual"])
data_frame21["mailnride_ezpay_exp"] = pd.to_numeric(data_frame21["mailnride_ezpay_exp"])
data_frame21["mailnride_ezpay_unl"] = pd.to_numeric(data_frame21["mailnride_ezpay_unl"])
data_frame21["path_2trip"] = pd.to_numeric(data_frame21["path_2trip"])
data_frame21["airtrain_fullfare"] = pd.to_numeric(data_frame21["airtrain_fullfare"])
data_frame21["airtrain_30day"] = pd.to_numeric(data_frame21["airtrain_30day"])
data_frame21["airtrain_10trip"] = pd.to_numeric(data_frame21["airtrain_10trip"])
data_frame21["airtrain_monthly"] = pd.to_numeric(data_frame21["airtrain_monthly"])
data_frame21["student"] = pd.to_numeric(data_frame21["student"])
data_frame21["Nice_2trip"] = pd.to_numeric(data_frame21["Nice_2trip"])
data_frame21["cuny_120d"] = pd.to_numeric(data_frame21["cuny_120d"])
data_frame21["cuny_60d"] = pd.to_numeric(data_frame21["cuny_60d"])
data_frame21["full_farevalue"] = pd.to_numeric(data_frame21["full_farevalue"])
data_frame21["full_fare7d"] = pd.to_numeric(data_frame21["full_fare7d"])
data_frame21["full_fare30d"] = pd.to_numeric(data_frame21["full_fare30d"])

NameError: name 'pd' is not defined

In [22]:
stations21 = data_frame21.station.unique().tolist()
len(stations21)

472

In [30]:
grouped_data21 = {}
for station in stations21:
    df = data_frame21.loc[data_frame21["station"] == station]
    grouped_data21[station] = df

In [31]:
grouped_data21_by_months = {}
for station in stations21:
    df = grouped_data21[station]
    january21_df = df.loc[df["month"] == "january"]
    february21_df = df.loc[df["month"] == "february"]
    march21_df = df.loc[df["month"] == "march"]
    april21_df = df.loc[df["month"] == "april"]
    grouped_data21_by_months[station] = {
        "january": january21_df,
        "february": february21_df,
        "march": march21_df,
        "april": april21_df
    }

In [32]:
grouped_data21_by_months[stations21[0]]["january"].sum(axis=1).sum()

109512

In [33]:
total21_by_months = {}
for station in stations21:
    print(f"On Station {station} -> {stations21.index(station)} of {len(stations21)}")
    total21_by_months[station] = {}
    for month in grouped_data21_by_months[station]:
        df = grouped_data21_by_months[station][month]
        total_swiped21 = df.sum(axis=1).sum()
        total21_by_months[station][month] = {
            "total_card_swiped": total_swiped21
        }

On Station WHITEHALL STREET               -> 0 of 472
On Station CYPRESS HILLS                  -> 1 of 472
On Station 75TH STREET & ELDERTS LANE     -> 2 of 472
On Station 85TH STREET & FOREST PKWAY     -> 3 of 472
On Station WOODHAVEN BOULEVARD            -> 4 of 472
On Station 104TH STREET                   -> 5 of 472
On Station 111TH STREET                   -> 6 of 472
On Station 121ST STREET                   -> 7 of 472
On Station 42ND STREET & 8TH AVENUE       -> 8 of 472
On Station 34TH STREET & 8TH AVENUE       -> 9 of 472
On Station FULTON STREET                  -> 10 of 472
On Station FIFTH AVENUE                   -> 11 of 472
On Station LEXINGTON AVENUE               -> 12 of 472
On Station ROOSEVELT AVE/JACKSON HTS      -> 13 of 472
On Station 179TH STREET & HILLSIDE AVE    -> 14 of 472
On Station 47-50 STREETS/ROCKEFELLER      -> 15 of 472
On Station 42ND STREET & 6TH AVENUE       -> 16 of 472
On Station 34TH STREET & 6TH AVENUE       -> 17 of 472
On Station SUTPHIN BOULEVARD              -> 18 of 472
On Station JAMAICA CENTER-PARSONS BLVD    -> 19 of 472
On Station WALL STREET                    -> 20 of 472
On Station FULTON & WILLIAM STREETS       -> 21 of 472
On Station PARK PLACE                     -> 22 of 472
On Station CHAMBERS STREET                -> 23 of 472
On Station 34TH STREET & 7TH AVENUE       -> 24 of 472
On Station 42ND STREET/TIMES SQUARE       -> 25 of 472
On Station 125TH STREET & BROADWAY        -> 26 of 472
On Station 168TH STREET & BROADWAY        -> 27 of 472
On Station DYCKMAN STREET                 -> 28 of 472
On Station 207TH STREET                   -> 29 of 472
On Station 215TH STREET                   -> 30 of 472
On Station 225TH STREET                   -> 31 of 472
On Station 231ST STREET                   -> 32 of 472
On Station BOWLING GREEN & BATTERY PL     -> 33 of 472
On Station BOWLING GREEN & BROADWAY       -> 34 of 472
On Station BROOKLYN BRIDGE                -> 35 of 472
On Station 42ND STREET & GRAND CENTRAL    -> 36 of 472
On Station 42ND STREET & 3RD AVENUE       -> 37 of 472
On Station 51ST STREET & LEXINGTON AVE    -> 38 of 472
On Station 59TH STREET & LEXINGTON AVE    -> 39 of 472
On Station WOODLAWN ROAD                  -> 40 of 472
On Station 149TH STREET & 3RD AVENUE      -> 41 of 472
On Station FIFTH AVENUE & 42ND STREET     -> 42 of 472
On Station MAIN STREET                    -> 43 of 472
On Station NEVINS STREET                  -> 44 of 472
On Station BARCLAYS CENTER                -> 45 of 472
On Station BERGEN STREET                  -> 46 of 472
On Station GRAND ARMY PLAZA               -> 47 of 472
On Station EASTERN PARKWAY                -> 48 of 472
On Station NOSTRAND AVENUE                -> 49 of 472
On Station UTICA AVENUE                   -> 50 of 472
On Station SUTTER AVENUE                  -> 51 of 472
On Station SARATOGA AVENUE                -> 52 of 472
On Station ROCKAWAY AVENUE                -> 53 of 472
On Station JUNIUS STREET                  -> 54 of 472
On Station PENNSYLVANIA AVENUE            -> 55 of 472
On Station VAN SICLEN AVENUE              -> 56 of 472
On Station NEW LOTS AVENUE                -> 57 of 472
On Station ST GEORGE TERMINAL             -> 58 of 472
On Station 34TH STREET - HUDSON YARDS     -> 59 of 472
On Station FIFTH AVENUE & 60TH STREET     -> 60 of 472
On Station 57TH STREET & 7TH AVENUE       -> 61 of 472
On Station 49TH STREET & 7TH AVENUE       -> 62 of 472
On Station 28TH STREET & BROADWAY         -> 63 of 472
On Station 23RD STREET & 5TH AVENUE       -> 64 of 472
On Station 59TH STREET/COLUMBUS CIRCLE    -> 65 of 472
On Station 8TH STREET & BROADWAY          -> 66 of 472
On Station PRINCE STREET & BROADWAY       -> 67 of 472
On Station CITY HALL                      -> 68 of 472
On Station CORTLANDT STREET               -> 69 of 472
On Station JAY ST-METROTECH               -> 70 of 472
On Station 39TH AVENUE & 31ST STREET      -> 71 of 472
On Station 36TH AVENUE & 31ST STREET      -> 72 of 472
On Station BROADWAY & 31ST STREET         -> 73 of 472
On Station 30TH AVENUE & 31ST STREET      -> 74 of 472
On Station ASTORIA BLVD & 31ST STREET     -> 75 of 472
On Station DITMARS BLVD & 31ST STREET     -> 76 of 472
On Station 82ND STREET-JACKSON HEIGHTS    -> 77 of 472
On Station JUNCTION BLVD-ROOSEVELT AVE    -> 78 of 472
On Station CHURCH AVENUE                  -> 79 of 472
On Station DEKALB AVENUE                  -> 80 of 472
On Station METROPOLITAN AVENUE            -> 81 of 472
On Station 145TH STREET                   -> 82 of 472
On Station 125TH STREET                   -> 83 of 472
On Station BROADWAY-EAST NEW YORK         -> 84 of 472
On Station 167TH ST-GRAND CONCOURSE       -> 85 of 472
On Station 14TH STREET & 7TH AVENUE       -> 86 of 472
On Station CASTLE HILL AVENUE             -> 87 of 472
On Station WESTCHESTER SQUARE             -> 88 of 472
On Station BOROUGH HALL - COURT STREET    -> 89 of 472
On Station CHURCH AVENUE & NOSTRAND AV    -> 90 of 472
On Station FLATBUSH AVE & NOSTRAND AV     -> 91 of 472
On Station 23RD STREET & 8TH AVENUE       -> 92 of 472
On Station FORDHAM RD/GRAND CONCOURSE     -> 93 of 472
On Station SEVENTH AVENUE & WEST 53RD     -> 94 of 472
On Station PARSONS BLVD & HILLSIDE AV     -> 95 of 472
On Station 169TH STREET & HILLSIDE AVE    -> 96 of 472
On Station 50TH STREET & 7TH AVENUE       -> 97 of 472
On Station 242ND STREET & BROADWAY        -> 98 of 472
On Station CANAL STREET                   -> 99 of 472
On Station FORDHAM ROAD & JEROME AVE      -> 100 of 472
On Station MORRISON AVE & WESTCHESTER     -> 101 of 472
On Station QUEENSBORO PLAZA               -> 102 of 472
On Station 90TH STREET/ELMHURST AVENUE    -> 103 of 472
On Station FRANKLIN AVE/EASTERN PKWY      -> 104 of 472
On Station KINGSTON AVE/EASTERN PKWY      -> 105 of 472
On Station BROAD STREET & WALL STREET     -> 106 of 472
On Station 175TH STREET/FT WASHINGTON     -> 107 of 472
On Station SUTPHIN BLVD-HILLSIDE AVE      -> 108 of 472
On Station BERGEN STREET-SMITH STREET     -> 109 of 472
On Station KINGS HIGHWAY-MCDONALD AVE     -> 110 of 472
On Station 23RD STREET-PARK AVE SOUTH     -> 111 of 472
On Station 125TH STREET-LEXINGTON AVE     -> 112 of 472
On Station MOSHOLU PARKWAY-JEROME AVE     -> 113 of 472
On Station HUNTERS PT AVE-49TH AVE        -> 114 of 472
On Station NEWKIRK AVE-NOSTRAND AVE       -> 115 of 472
On Station SHEEPSHEAD BAY ROAD            -> 116 of 472
On Station MYRTLE AVE-GATES AVENUE        -> 117 of 472
On Station WEST 4TH ST-WASHINGTON SQ      -> 118 of 472
On Station CANAL STREET-LISPENARD ST      -> 119 of 472
On Station QUEENS PLAZA-JACKSON AVE       -> 120 of 472
On Station 71ST AVE-CONTINENTAL AVE       -> 121 of 472
On Station ESSEX ST-DELANCEY ST           -> 122 of 472
On Station 28TH STREET-PARK AVE SOUTH     -> 123 of 472
On Station 96TH STREET-LEXINGTON AVE      -> 124 of 472
On Station 241ST ST-WHITE PLAINS RD       -> 125 of 472
On Station HUNTS PT AVE-SOUTHERN BLVD     -> 126 of 472
On Station 61ST STREET-ROOSEVELT AVE      -> 127 of 472
On Station PARKSIDE AVE-OCEAN AVE         -> 128 of 472
On Station NEWKIRK PLAZA                  -> 129 of 472
On Station AVENUE U-EAST 16TH STREET      -> 130 of 472
On Station STILLWELL AVE-CONEY ISLAND     -> 131 of 472
On Station ROCKAWAY PKWY-GLENWOOD RD      -> 132 of 472
On Station UTICA AVE-STUYVESANT AVE       -> 133 of 472
On Station TREMONT AVE-179TH ST           -> 134 of 472
On Station KINGSBRIDGE RD-196TH ST        -> 135 of 472
On Station BEDFORD PARK BLVD-203RD ST     -> 136 of 472
On Station 205TH ST-BAINBRIDGE AVE        -> 137 of 472
On Station UNION TURNPIKE-KEW GARDENS     -> 138 of 472
On Station 116TH STREET-COLUMBIA          -> 139 of 472
On Station ASTOR PLACE-4 AVENUE           -> 140 of 472
On Station KINGSBRIDGE RD-JEROME AVE      -> 141 of 472
On Station ELDER AVE-WESTCHESTER AVE      -> 142 of 472
On Station 14TH STREET-6TH AVENUE         -> 143 of 472
On Station 66TH STREET-BROADWAY           -> 144 of 472
On Station TOMPKINSVILLE                  -> 145 of 472
On Station 79TH STREET-BROADWAY           -> 146 of 472
On Station 86TH STREET-BROADWAY           -> 147 of 472
On Station 96TH STREET-BROADWAY           -> 148 of 472
On Station 137TH STREET-BROADWAY          -> 149 of 472
On Station 14TH STREET-UNION SQUARE       -> 150 of 472
On Station 7TH AVENUE-PARK PLACE          -> 151 of 472
On Station BRIGHTON BEACH-CONEY ISLAND    -> 152 of 472
On Station 207TH STREET-BROADWAY          -> 153 of 472
On Station 181ST STREET-FT WASH AVE       -> 154 of 472
On Station 8TH AVENUE-14TH STREET         -> 155 of 472
On Station 33RD STREET-PARK AVENUE        -> 156 of 472
On Station 68TH STREET-HUNTER COLLEGE     -> 157 of 472
On Station 77TH STREET-LEXINGTON AVE      -> 158 of 472
On Station 86TH STREET-LEXINGTON AVE      -> 159 of 472
On Station 103RD STREET-LEXINGTON AVE     -> 160 of 472
On Station 110TH STREET-LEXINGTON AVE     -> 161 of 472
On Station 116TH STREET-LEXINGTON AVE     -> 162 of 472
On Station BEDFORD PARK BLVD-JEROME AV    -> 163 of 472
On Station CORTELYOU RD-EAST 16TH ST      -> 164 of 472
On Station DYCKMAN STREET-BROADWAY        -> 165 of 472
On Station 86TH ST-CENTRAL PARK WEST      -> 166 of 472
On Station 81ST STREET-MUSEUM             -> 167 of 472
On Station 50TH STREET-8TH AVENUE         -> 168 of 472
On Station CHRISTOPHER ST-SHERIDAN SQ     -> 169 of 472
On Station 23RD STREET-7TH AVENUE         -> 170 of 472
On Station 103RD STREET-BROADWAY          -> 171 of 472
On Station 110TH STREET-BROADWAY          -> 172 of 472
On Station 157TH STREET-BROADWAY          -> 173 of 472
On Station BLEECKER ST-LAFAYETTE ST       -> 174 of 472
On Station 161ST STREET-YANKEE STADIUM    -> 175 of 472
On Station PROSPECT PARK-EMPIRE BLVD      -> 176 of 472
On Station 36TH STREET-4TH AVENUE         -> 177 of 472
On Station NOSTRAND AVE-FULTON ST         -> 178 of 472
On Station KINGSTON AVE-THROOP AVE        -> 179 of 472
On Station EUCLID AVE-PITKIN AVE          -> 180 of 472
On Station WOODHAVEN BLVD-QUEENS BLVD     -> 181 of 472
On Station 63RD DRIVE-REGO PARK           -> 182 of 472
On Station 23RD STREET-6TH AVENUE         -> 183 of 472
On Station CHURCH AVE-MCDONALD AVE        -> 184 of 472
On Station 149TH ST-GRAND CONCOURSE       -> 185 of 472
On Station 125TH STREET-LENOX AVENUE      -> 186 of 472
On Station 135TH STREET-LENOX AVENUE      -> 187 of 472
On Station 103RD ST-ROOSEVELT AVE         -> 188 of 472
On Station STERLING ST-NOSTRAND AVE       -> 189 of 472
On Station BEVERLY RD-NOSTRAND AVE        -> 190 of 472
On Station KINGS HIGHWAY-EAST 16TH ST     -> 191 of 472
On Station 59TH STREET-4TH AVENUE         -> 192 of 472
On Station BAY RIDGE AVE-4TH AVENUE       -> 193 of 472
On Station 77TH STREET-4TH AVENUE         -> 194 of 472
On Station 86TH STREET-4TH AVENUE         -> 195 of 472
On Station BAY RIDGE - 95TH STREET        -> 196 of 472
On Station HOYT ST-SCHERMERHORN ST        -> 197 of 472
On Station ELMHURST AVE-BROADWAY          -> 198 of 472
On Station 67TH AVENUE-QUEENS BLVD        -> 199 of 472
On Station CARROLL ST-PRESIDENT ST        -> 200 of 472
On Station 167TH STREET-RIVER AVENUE      -> 201 of 472
On Station 177TH STREET-PARKCHESTER       -> 202 of 472
On Station 46TH ST-BLISS ST               -> 203 of 472
On Station CLARK STREET-HENRY STREET      -> 204 of 472
On Station HOYT STREET-HOYT STREET        -> 205 of 472
On Station GUN HILL ROAD-SEYMOUR          -> 206 of 472
On Station RECTOR STREET-CHURCH STREET    -> 207 of 472
On Station AVENUE J-EAST 16TH STREET      -> 208 of 472
On Station AVENUE M-EAST 16TH STREET      -> 209 of 472
On Station NECK ROAD-EAST 16TH STREET     -> 210 of 472

On Station UNION STREET-4TH AVENUE        -> 211 of 472
On Station 45TH STREET-4TH AVENUE         -> 212 of 472
On Station 53RD STREET-4TH AVENUE         -> 213 of 472
On Station 50TH STREET-NEW UTRECHT AVE    -> 214 of 472
On Station BEDFORD AVE-NORTH 7TH ST       -> 215 of 472
On Station DEKALB AVE-WYCKOFF AVE         -> 216 of 472
On Station 182ND STREET-183RD STREET      -> 217 of 472
On Station STEINWAY ST-BROADWAY           -> 218 of 472
On Station GREENPOINT AVE                 -> 219 of 472
On Station GRAND ST-CHRISTIE ST           -> 220 of 472
On Station 15TH ST-PROSPECT PARK WEST     -> 221 of 472
On Station 18TH AVE-MCDONALD AVE          -> 222 of 472
On Station 170TH STREET-JEROME AVENUE     -> 223 of 472
On Station BURNSIDE AVE-JEROME AVE        -> 224 of 472
On Station ST LAWRENCE AVE-WEST AVE       -> 225 of 472
On Station PROSPECT AVENUE-4TH AVENUE     -> 226 of 472
On Station 55TH ST-NEW UTRECHT AVE        -> 227 of 472
On Station 1ST AVENUE-14TH STREET         -> 228 of 472
On Station GRAHAM AVE-METROPOLITAN AVE    -> 229 of 472
On Station GRAND ST-BUSHWICK AVE          -> 230 of 472
On Station 96TH ST-CENTRAL PARK WEST      -> 231 of 472
On Station HIGH ST-CADMAN PLAZA WEST      -> 232 of 472
On Station 174TH-175TH ST-GRAND CONCOU    -> 233 of 472
On Station GRAND AVE-QUEENS BOULEVARD     -> 234 of 472
On Station VAN WYCK BLVD-MAIN STREET      -> 235 of 472
On Station NASSAU AVE-MANHATTAN AVE       -> 236 of 472
On Station EAST BROADWAY-MADISON ST       -> 237 of 472
On Station 4TH AVENUE-9TH STREET          -> 238 of 472
On Station ROOSEVELT ISLAND               -> 239 of 472
On Station 40TH STREET-LOWERY STREET      -> 240 of 472
On Station BEVERLEY ROAD -EAST 15TH ST    -> 241 of 472
On Station AVENUE H-EAST 16TH STREET      -> 242 of 472
On Station OCEAN PKWAY-BRIGHTON BCH AV    -> 243 of 472
On Station MONTROSE AVENUE                -> 244 of 472
On Station HALSEY STREET-WYCKOFF AVE      -> 245 of 472
On Station 46TH STREET-BROADWAY           -> 246 of 472
On Station METROPOLITAN AVE-LORIMER ST    -> 247 of 472
On Station BEDFORD AVENUE-NOSTRAND AVE    -> 248 of 472
On Station SMITH STREET-9TH STREET        -> 249 of 472
On Station AVENUE X-MCDONALD AVENUE       -> 250 of 472
On Station 28TH STREET-7TH AVENUE         -> 251 of 472
On Station 145TH STREET-BROADWAY          -> 252 of 472
On Station 191ST STREET-ST NICHOLAS AV    -> 253 of 472
On Station 183RD STREET-JEROME AVENUE     -> 254 of 472
On Station JACKSON AVENUE-VERNON BLVD     -> 255 of 472
On Station PRESIDENT ST-NOSTRAND AVE      -> 256 of 472
On Station 25TH STREET-4TH AVENUE         -> 257 of 472
On Station JEFFERSON STREET-WYCKOFF AV    -> 258 of 472
On Station 190TH STREET-OVERLOOK TERR     -> 259 of 472
On Station 72ND STREET-CENTRAL PK WEST    -> 260 of 472
On Station SPRING STREET-6TH AVENUE       -> 261 of 472
On Station LAFAYETTE AVENUE-FULTON ST     -> 262 of 472
On Station CLINTON AVENUE-FULTON ST       -> 263 of 472
On Station MOTT AVENUE-BEACH 22ND ST      -> 264 of 472
On Station MYRTLE AVENUE-MARCY AVENUE     -> 265 of 472
On Station CLASSON AVENUE-LAFAYETTE AV    -> 266 of 472
On Station 7TH AVENUE-9TH STREET          -> 267 of 472
On Station FT HAMILTON PKY-GREENWOOD      -> 268 of 472
On Station HOUSTON STREET-VARICK ST       -> 269 of 472
On Station 33RD STREET-QUEENS BLVD        -> 270 of 472
On Station BAYCHESTER AVE-TILLOTSON       -> 271 of 472
On Station 34TH STREET - PENN STATION     -> 272 of 472
On Station MORGAN AVENUE-HARRISON PL      -> 273 of 472
On Station WILSON AVENUE-MOFFAT STREET    -> 274 of 472
On Station 163RD ST & AMSTERDAM AVE       -> 275 of 472
On Station FRANKLIN AVENUE-FULTON ST      -> 276 of 472
On Station NORTHERN BLVD-BROADWAY         -> 277 of 472
On Station BROADWAY - UNION AVENUE        -> 278 of 472
On Station 2ND AVENUE-HOUSTON STREET      -> 279 of 472
On Station YORK STREET-JAY STREET         -> 280 of 472
On Station 57TH STREET-6TH AVENUE         -> 281 of 472
On Station 21ST STREET-QUEENSBRIDGE       -> 282 of 472
On Station RECTOR STREET-GREENWICH ST     -> 283 of 472
On Station WTC-CORTLANDT ST               -> 284 of 472
On Station 238TH STREET-BROADWAY          -> 285 of 472
On Station 138TH ST-GRAND CONCOURSE       -> 286 of 472
On Station MT EDEN AVENUE-JEROME AVE      -> 287 of 472
On Station 176TH STREET-JEROME AVENUE     -> 288 of 472
On Station 111TH STREET-ROOSEVELT AVE     -> 289 of 472
On Station BOWERY STREET-DELANCEY ST      -> 290 of 472
On Station WEST 6TH STREET-SURF AVENUE    -> 291 of 472
On Station BUSHWICK AVENUE-ABERDEEN ST    -> 292 of 472
On Station 103RD ST-CENTRAL PARK WEST     -> 293 of 472
On Station 155TH STREET-8TH AVENUE        -> 294 of 472
On Station FLUSHING AVENUE-MARCY AVE      -> 295 of 472
On Station LAFAYETTE AV-WASHINGTON AV     -> 296 of 472
On Station FULTON STREET-LAFAYETTE AV     -> 297 of 472
On Station 63RD STREET-LEXINGTON AVE      -> 298 of 472
On Station CANAL STREET-VARICK STREET     -> 299 of 472
On Station 18TH STREET-7TH AVENUE         -> 300 of 472
On Station SPRING STREET-LAFAYETTE ST     -> 301 of 472
On Station 111TH STREET-LENOX AVENUE      -> 302 of 472
On Station 116TH STREET-LENOX AVENUE      -> 303 of 472
On Station WHITLOCK AVE-WESTCHESTER AV    -> 304 of 472
On Station ZEREGA AVE-WESTCHESTER AVE     -> 305 of 472
On Station 52ND STREET-ROOSEVELT AVE      -> 306 of 472
On Station WILLETS PT BLVD-ROOSEVELT      -> 307 of 472
On Station MORRIS PARK-PAULDING AVENUE    -> 308 of 472
On Station 3RD AVENUE-14TH STREET         -> 309 of 472
On Station 155TH STREET-ST NICHOLAS AV    -> 310 of 472
On Station 135TH STREET-ST NICHOLAS AV    -> 311 of 472
On Station 116TH STREET-8TH AVENUE        -> 312 of 472
On Station 110TH STREET-8TH AVENUE        -> 313 of 472
On Station GASTON AVENUE-BEACH 67TH ST    -> 314 of 472
On Station STRAITON AVE-BEACH 60TH ST     -> 315 of 472
On Station FRANK AVENUE-BEACH 44TH ST     -> 316 of 472
On Station EDGEMERE-BEACH 36TH STREET     -> 317 of 472
On Station 36TH STREET-NORTHERN BLVD      -> 318 of 472
On Station 65TH STREET-BROADWAY           -> 319 of 472
On Station 75TH AVENUE-QUEENS BLVD        -> 320 of 472
On Station VAN WYCK BLVD-METROPOLITAN     -> 321 of 472
On Station FRANKLIN STREET-WEST BWAY      -> 322 of 472
On Station 145TH STREET-LENOX AVENUE      -> 323 of 472
On Station 148TH STREET-LENOX AVENUE      -> 324 of 472
On Station COURT SQ                       -> 325 of 472
On Station 69TH STREET-ROOSEVELT AVE      -> 326 of 472
On Station ATLANTIC AV-VAN SINDEREN AV    -> 327 of 472
On Station SUTTER AVE-VAN SINDEREN AVE    -> 328 of 472
On Station LIVONIA AVE-VAN SINDEREN AV    -> 329 of 472
On Station HEWES STREET-BROADWAY          -> 330 of 472
On Station LORIMER STREET-BROADWAY        -> 331 of 472
On Station 104TH STREET-LIBERTY AVENUE    -> 332 of 472
On Station 109TH STREET-LIBERTY AVENUE    -> 333 of 472
On Station LEFFERTS BLVD-LIBERTY AVE      -> 334 of 472
On Station NORTH CONDUIT AVE-COHANCEY     -> 335 of 472
On Station BEACH 25TH STREET-WAVECREST    -> 336 of 472
On Station COURT SQ-23 ST                 -> 337 of 472
On Station 21ST STREET-JACKSON AVENUE     -> 338 of 472
On Station PELHAM PKWY-WHITE PLAINS RD    -> 339 of 472
On Station ALLERTON AV-WHITE PLAINS RD    -> 340 of 472
On Station BURKE AVE-WHITE PLAINS ROAD    -> 341 of 472
On Station GUNHILL RD-WHITE PLAINS RD     -> 342 of 472
On Station 219TH ST-WHITE PLAINS ROAD     -> 343 of 472
On Station 225TH ST-WHITE PLAINS ROAD     -> 344 of 472
On Station 233RD ST-WHITE PLAINS ROAD     -> 345 of 472
On Station 9TH AVENUE-39TH STREET         -> 346 of 472
On Station FORT HAMILTON PKWY-45TH ST     -> 347 of 472
On Station 71ST STREET-NEW UTRECHT AVE    -> 348 of 472
On Station 79TH STREET-17TH AVENUE        -> 349 of 472
On Station 18TH AVENUE-86TH STREET        -> 350 of 472
On Station 20TH AVENUE-86TH STREET        -> 351 of 472
On Station BAY PARKWAY-86TH STREET        -> 352 of 472
On Station NEW LOTS AV-VAN SINDEREN AV    -> 353 of 472
On Station EAST 105TH ST-FARRAGUT ROAD    -> 354 of 472
On Station FLUSHING AVE-BROADWAY          -> 355 of 472
On Station MYRTLE AVENUE-BROADWAY         -> 356 of 472
On Station KOSCIUSZKO STREET-BROADWAY     -> 357 of 472
On Station GATES AVENUE-BROADWAY          -> 358 of 472
On Station HALSEY STREET-BROADWAY         -> 359 of 472
On Station GRANT AVENUE-PITKIN AVENUE     -> 360 of 472
On Station HUDSON STREET-78TH STREET      -> 361 of 472
On Station BOYD STREET-88TH STREET        -> 362 of 472
On Station ROCKAWAY BLVD-LIBERTY AVE      -> 363 of 472
On Station 174TH STREET-SOUTHERN BLVD     -> 364 of 472
On Station EAST TREMONT AVENUE-178 ST     -> 365 of 472
On Station EAST 180TH ST-MORRIS PARK      -> 366 of 472
On Station BRONX PARK EAST                -> 367 of 472
On Station 8TH AVENUE-62ND STREET         -> 368 of 472
On Station FORT HAMILTON PARKWAY-62ND     -> 369 of 472
On Station 18TH AVENUE-62ND STREET        -> 370 of 472
On Station 20TH AVENUE-62ND STREET        -> 371 of 472
On Station BAY PARKWAY-66TH STREET        -> 372 of 472
On Station KINGS HIGHWAY-WEST 7TH ST      -> 373 of 472
On Station AVENUE U-WEST 7TH STREET       -> 374 of 472
On Station 86TH STREET-AVENUE V           -> 375 of 472
On Station NEW UTRECHT AVENUE-62ND ST     -> 376 of 472
On Station 25TH AVENUE-86TH STREET        -> 377 of 472
On Station BAY 50TH STREET-STILLWELL      -> 378 of 472
On Station CENTRAL AVE-MYRTLE AVE         -> 379 of 472
On Station SENECA AVENUE-PALMETTO ST      -> 380 of 472
On Station FOREST AVENUE-PUTNAM AVENUE    -> 381 of 472
On Station FRESH POND ROAD-68TH AVENUE    -> 382 of 472
On Station JACKSON AVENUE-WESTCHESTER     -> 383 of 472
On Station PROSPECT AVENUE-WESTCHESTER    -> 384 of 472
On Station INTERVALE 163RD STREET         -> 385 of 472
On Station SIMPSON ST-WESTCHESTER AVE     -> 386 of 472
On Station FREEMAN ST-SOUTHERN BLVD       -> 387 of 472
On Station PARK PLACE-FRANKLIN AVENUE     -> 388 of 472
On Station BOTANIC GARDEN-FRANKLIN AVE    -> 389 of 472
On Station KNICKERBOCKER AVE-MYRTLE AV    -> 390 of 472
On Station HOWARD BEACH-159TH AVE         -> 391 of 472
On Station BROAD CHANNEL-NOEL ROAD        -> 392 of 472
On Station HOLLAND-BEACH 90TH STREET      -> 393 of 472
On Station PLAYLAND-BEACH 98TH STREET     -> 394 of 472
On Station SEASIDE BEACH-105TH STREET     -> 395 of 472
On Station ROCKAWAY PARK-BEACH 116TH      -> 396 of 472
On Station DITMAS AVE-MCDONALD AVE        -> 397 of 472
On Station AVENUE I-MCDONALD AVENUE       -> 398 of 472
On Station MCDONALD AVE-22ND AVE          -> 399 of 472
On Station AVENUE N-MCDONALD AVENUE       -> 400 of 472
On Station AVENUE P-MCDONALD AVENUE       -> 401 of 472
On Station AVENUE U-MCDONALD AVENUE       -> 402 of 472
On Station NEPTUNE AVE-MCDONALD AVENUE    -> 403 of 472
On Station MIDDLETOWN ROAD-WESTCHESTER    -> 404 of 472
On Station BUHRE AVE-WESTCHESTER AVE      -> 405 of 472
On Station PELHAM BAY PARK-BRUCKNER BL    -> 406 of 472
On Station PELHAM PKWY-ESPLANADE          -> 407 of 472
On Station DYRE AVENUE-LIGHT STREET       -> 408 of 472
On Station CHAUNCEY STREET-ROCKAWAY AV    -> 409 of 472
On Station ALABAMA AVENUE-FULTON ST       -> 410 of 472
On Station VAN SICLEN AVENUE-FULTON ST    -> 411 of 472
On Station CLEVELAND STREET-FULTON ST     -> 412 of 472
On Station NORWOOD AVENUE-FULTON ST       -> 413 of 472
On Station CRESCENT STREET-FULTON ST      -> 414 of 472

On Station RALPH AVENUE-FULTON STREET     -> 415 of 472
On Station ROCKAWAY AVE-HOPKINSON AVE     -> 416 of 472
On Station LIBERTY AVE-PENNSYLVANIA AV    -> 417 of 472
On Station VAN SICLEN AVE-PITKIN AVE      -> 418 of 472
On Station SHEPHERD AVE-PITKIN AVE        -> 419 of 472
On Station 170TH STREET-GRAND CONC.       -> 420 of 472
On Station 238TH ST-WHITE PLAINS ROAD     -> 421 of 472
On Station 138TH STREET-3RD AVE           -> 422 of 472
On Station BROOK AVENUE-138TH STREET      -> 423 of 472
On Station CYPRESS AVENUE-138TH STREET    -> 424 of 472
On Station EAST 143RD ST-SOUTHERN BLVD    -> 425 of 472
On Station EAST 149TH ST-SOUTHERN BLVD    -> 426 of 472
On Station LONGWOOD AVE-SOUTHERN BLVD     -> 427 of 472
On Station WINTHROP ST-NOSTRAND AVE       -> 428 of 472
On Station 72ND STREET & BROADWAY         -> 429 of 472
On Station HOYT STREET-FULTON STREET      -> 430 of 472
On Station MARCY AVENUE-BROADWAY          -> 431 of 472
On Station BROADWAY LAFAYETTE-BLEECKER    -> 432 of 472
On Station CANAL STREET-BROADWAY          -> 433 of 472
On Station CANAL ST-LAFAYETTE ST EAST     -> 434 of 472
On Station AQUEDUCT RACE TRACK            -> 435 of 472
On Station RI TRAMWAY (MANHATTAN)         -> 436 of 472
On Station RI TRAMWAY (ROOSEVELT)         -> 437 of 472
On Station AIRTRAIN @ HOWARD BEACH        -> 438 of 472
On Station AIRTRAIN JAMAICA CENTER 1      -> 439 of 472
On Station PA-PATH WORLD TRADE CNTR       -> 440 of 472
On Station PA-PATH THIRTY THIRD ST        -> 441 of 472
On Station PA-PATH TWENTY THIRD ST        -> 442 of 472
On Station PA-PATH EXCHANGE PLACE         -> 443 of 472
On Station PA-PATH HARRISON               -> 444 of 472
On Station PA-PATH 14TH STREET            -> 445 of 472
On Station PA-PATH PAVONIA/NEWPORT        -> 446 of 472
On Station PA-PATH 9TH STREET             -> 447 of 472
On Station PA-PATH CHRISTOPHER ST         -> 448 of 472
On Station PA-PATH NEWARK                 -> 449 of 472
On Station PA-PATH HOBOKEN                -> 450 of 472
On Station PA-PATH GROVE ST               -> 451 of 472
On Station PA-PATH JOURNAL SQUARE         -> 452 of 472
On Station 72ND STREET - 2 AVENUE         -> 453 of 472
On Station 86TH STREET - 2 AVENUE         -> 454 of 472
On Station 96TH STREET - 2 AVENUE         -> 455 of 472
On Station SBS-M15 @ LIVINGSTON PLAZA     -> 456 of 472
On Station SBS-BX12 @ LIVINGSTON PLAZA    -> 457 of 472
On Station SBS-M34 @ LIVINGSTON PLAZA     -> 458 of 472
On Station SBS-BX41 @ LIVINGSTON PLAZA    -> 459 of 472
On Station SBS-B44 @ LIVINGSTON PLAZA     -> 460 of 472
On Station SBS-M60 @ LIVINGSTON PLAZA     -> 461 of 472
On Station SBS-M86 @ LIVINGSTON PLAZA     -> 462 of 472
On Station MTABC - EASTCHESTER 2          -> 463 of 472
On Station SBS-B46 @ LIVINGSTON PLAZA     -> 464 of 472
On Station SBS-Q44 @ LIVINGSTON PLAZA     -> 465 of 472
On Station SBS-M23 @ LIVINGSTON PLAZA     -> 466 of 472
On Station SBS-M79 @ LIVINGSTON PLAZA     -> 467 of 472
On Station SBS-BX6 @ LIVINGSTON PLAZA     -> 468 of 472
On Station SBS-Q52/53 @ LIVINGSTON PLAZA  -> 469 of 472
On Station SBS-B82 @ LIVINGSTON PLAZA     -> 470 of 472
On Station SBS-M14 @ LIVINGSTON PLAZA     -> 471 of 472

In [34]:
total21_by_months[stations21[0]]["february"]["total_card_swiped"]

92599

In [35]:
total21_by_months[stations21[0]]

{'january': {'total_card_swiped': 109512},
 'february': {'total_card_swiped': 92599},
 'march': {'total_card_swiped': 110429},
 'april': {'total_card_swiped': 121610}}

In [ ]:
CSV22_ALL SWIPES

# CSV22_ALL SWIPES

In [36]:
line_one = "     ,FARECARD"
line_two = "REMOTE, STATION,FF,SEN/DIS, 7-D AFAS UNL,30-D AFAS/RMF UNL,JOINT RR TKT,7-D UNL,30-D UNL,7D-XBUS PASS,TCMC,RF 2 TRIP,RR UNL NO TRADE,TCMC ANNUAL MC,MR EZPAY EXP,MR EZPAY UNL,PATH 2-T,AIRTRAIN FF,AIRTRAIN 30-D,AIRTRAIN 10-T,AIRTRAIN MTHLY,STUDENTS,NICE 2-T,CUNY-120,CUNY-60,FF VALUE,FF 7-DAY,FF 30-DAY"
data_dict22 = {
    "month": [],
    "station": [],
    "full_fare": [],
    "senior_discount": [],
    "seven_day_ADA": [],
    "thirty_day_ADA": [],
    "joint_rail_ticket": [],
    "seven_day_unlimited": [],
    "thirty_day_unlimited": [],
    "seven_day_expbus_pass": [],
    "transit_check": [],
    "reduced_fare_twotrip": [],
    "railroad_unlimited": [],
    "transit_check_annual": [],
    "mailnride_ezpay_exp": [],
    "mailnride_ezpay_unl": [],
    "path_2trip": [],
    "airtrain_fullfare": [],
    "airtrain_30day": [],
    "airtrain_10trip": [],
    "airtrain_monthly": [],
    "student": [],
    "Nice_2trip": [],
    "cuny_120d": [],
    "cuny_60d": [],
    "full_farevalue": [],
    "full_fare7d": [],
    "full_fare30d": []
}

#grouping 2022 data
grouped_data_by_month = {
    "january": data_dict22,
    "february": data_dict22,
    "march": data_dict22,
    "april": data_dict22
}
month = ""

In [37]:
for line in fileinput.input(csv22_files):
    if line.startswith(line_one) or line.startswith(line_two):
        continue
    if len(line.split(",")) == 26:
        date_range = line.split(",")[1]
        month_number = int(date_range.split("-")[0].split("/")[0])
        if month_number == 1:
            month = "january"
        elif month_number == 2:
            month = "february"
        elif month_number == 3:
            month = "march"
        elif month_number == 4:
            month = "april"
        continue
    data = line.split(",")
    data_dict22["station"].append(data[1])
    data_dict22["full_fare"].append(int(data[2]))
    data_dict22["senior_discount"].append(int(data[3]))
    data_dict22["seven_day_ADA"].append(int(data[4]))
    data_dict22["thirty_day_ADA"].append(int(data[5]))
    data_dict22["joint_rail_ticket"].append(int(data[6]))
    data_dict22["seven_day_unlimited"].append(int(data[7]))
    data_dict22["thirty_day_unlimited"].append(int(data[8]))
    data_dict22["seven_day_expbus_pass"].append(int(data[9]))
    data_dict22["transit_check"].append(int(data[10]))
    data_dict22["reduced_fare_twotrip"].append(int(data[11]))
    data_dict22["railroad_unlimited"].append(int(data[12]))
    data_dict22["transit_check_annual"].append(int(data[13]))
    data_dict22["mailnride_ezpay_exp"].append(int(data[14]))
    data_dict22["mailnride_ezpay_unl"].append(int(data[15]))
    data_dict22["path_2trip"].append(int(data[16]))
    data_dict22["airtrain_fullfare"].append(int(data[17]))
    data_dict22["airtrain_30day"].append(int(data[18]))
    data_dict22["airtrain_10trip"].append(int(data[19]))
    data_dict22["airtrain_monthly"].append(int(data[20]))
    data_dict22["student"].append(int(data[21]))
    data_dict22["Nice_2trip"].append(int(data[22]))
    data_dict22["cuny_120d"].append(int(data[23]))
    data_dict22["cuny_60d"].append(int(data[24]))
    data_dict22["full_farevalue"].append(int(data[25]))
    data_dict22["full_fare7d"].append(int(data[26]))
    data_dict22["full_fare30d"].append(int(data[27]))
    data_dict22["month"].append(month)

In [38]:
data_frame22 = pd.DataFrame(data_dict22)
data_frame22["full_fare"] = pd.to_numeric(data_frame22["full_fare"])
data_frame22["senior_discount"] = pd.to_numeric(data_frame22["senior_discount"])
data_frame22["seven_day_ADA"] = pd.to_numeric(data_frame22["seven_day_ADA"])
data_frame22["thirty_day_ADA"] = pd.to_numeric(data_frame22["thirty_day_ADA"])
data_frame22["joint_rail_ticket"] = pd.to_numeric(data_frame22["joint_rail_ticket"])
data_frame22["seven_day_unlimited"] = pd.to_numeric(data_frame22["seven_day_unlimited"])
data_frame22["thirty_day_unlimited"] = pd.to_numeric(data_frame22["thirty_day_unlimited"])
data_frame22["seven_day_expbus_pass"] = pd.to_numeric(data_frame22["seven_day_expbus_pass"])
data_frame22["transit_check"] = pd.to_numeric(data_frame22["transit_check"])
data_frame22["reduced_fare_twotrip"] = pd.to_numeric(data_frame22["reduced_fare_twotrip"])
data_frame22["railroad_unlimited"] = pd.to_numeric(data_frame22["railroad_unlimited"])
data_frame22["transit_check_annual"] = pd.to_numeric(data_frame22["transit_check_annual"])
data_frame22["mailnride_ezpay_exp"] = pd.to_numeric(data_frame22["mailnride_ezpay_exp"])
data_frame22["mailnride_ezpay_unl"] = pd.to_numeric(data_frame22["mailnride_ezpay_unl"])
data_frame22["path_2trip"] = pd.to_numeric(data_frame22["path_2trip"])
data_frame22["airtrain_fullfare"] = pd.to_numeric(data_frame22["airtrain_fullfare"])
data_frame22["airtrain_30day"] = pd.to_numeric(data_frame22["airtrain_30day"])
data_frame22["airtrain_10trip"] = pd.to_numeric(data_frame22["airtrain_10trip"])
data_frame22["airtrain_monthly"] = pd.to_numeric(data_frame22["airtrain_monthly"])
data_frame22["student"] = pd.to_numeric(data_frame22["student"])
data_frame22["Nice_2trip"] = pd.to_numeric(data_frame22["Nice_2trip"])
data_frame22["cuny_120d"] = pd.to_numeric(data_frame22["cuny_120d"])
data_frame22["cuny_60d"] = pd.to_numeric(data_frame22["cuny_60d"])
data_frame22["full_farevalue"] = pd.to_numeric(data_frame22["full_farevalue"])
data_frame22["full_fare7d"] = pd.to_numeric(data_frame22["full_fare7d"])
data_frame22["full_fare30d"] = pd.to_numeric(data_frame22["full_fare30d"])

In [39]:
stations22 = data_frame22.station.unique().tolist()
len(stations22)

473

In [40]:
grouped_data22 = {}
for station in stations22:
    df = data_frame22.loc[data_frame22["station"] == station]
    grouped_data22[station] = df

In [41]:
grouped_data22_by_months = {}
for station in stations22:
    df = grouped_data22[station]
    january22_df = df.loc[df["month"] == "january"]
    february22_df = df.loc[df["month"] == "february"]
    march22_df = df.loc[df["month"] == "march"]
    april22_df = df.loc[df["month"] == "april"]
    grouped_data22_by_months[station] = {
        "january": january22_df,
        "february": february22_df,
        "march": march22_df,
        "april": april22_df
    }

In [42]:
grouped_data22_by_months[stations22[0]]["january"].sum(axis=1).sum()

175529

In [52]:
total22_by_months = {}
for station in stations22:
    print(f"On Station {station} -> {stations22.index(station)} of {len(stations22)}")
    total22_by_months[station] = {}
    for month in grouped_data22_by_months[station]:
        df = grouped_data22_by_months[station][month]
        total_swiped22 = df.sum(axis=1).sum()
        total22_by_months[station][month] = {
            "total_card_swiped": total_swiped22
        }

On Station WHITEHALL STREET               -> 0 of 473
On Station CYPRESS HILLS                  -> 1 of 473
On Station 75TH STREET & ELDERTS LANE     -> 2 of 473
On Station 85TH STREET & FOREST PKWAY     -> 3 of 473
On Station WOODHAVEN BOULEVARD            -> 4 of 473
On Station 104TH STREET                   -> 5 of 473
On Station 111TH STREET                   -> 6 of 473
On Station 121ST STREET                   -> 7 of 473
On Station 42ND STREET & 8TH AVENUE       -> 8 of 473
On Station 34TH STREET & 8TH AVENUE       -> 9 of 473
On Station FULTON STREET                  -> 10 of 473
On Station FIFTH AVENUE                   -> 11 of 473
On Station LEXINGTON AVENUE               -> 12 of 473
On Station ROOSEVELT AVE/JACKSON HTS      -> 13 of 473
On Station 179TH STREET & HILLSIDE AVE    -> 14 of 473
On Station 47-50 STREETS/ROCKEFELLER      -> 15 of 473
On Station 42ND STREET & 6TH AVENUE       -> 16 of 473
On Station 34TH STREET & 6TH AVENUE       -> 17 of 473
On Station SUTPHIN BOULEVARD              -> 18 of 473
On Station JAMAICA CENTER-PARSONS BLVD    -> 19 of 473
On Station WALL STREET                    -> 20 of 473
On Station FULTON & WILLIAM STREETS       -> 21 of 473
On Station PARK PLACE                     -> 22 of 473
On Station CHAMBERS STREET                -> 23 of 473
On Station 34TH STREET & 7TH AVENUE       -> 24 of 473
On Station 42ND STREET/TIMES SQUARE       -> 25 of 473
On Station 125TH STREET & BROADWAY        -> 26 of 473
On Station 168TH STREET & BROADWAY        -> 27 of 473
On Station DYCKMAN STREET                 -> 28 of 473
On Station 207TH STREET                   -> 29 of 473
On Station 215TH STREET                   -> 30 of 473
On Station 225TH STREET                   -> 31 of 473
On Station 231ST STREET                   -> 32 of 473
On Station BOWLING GREEN & BATTERY PL     -> 33 of 473
On Station BOWLING GREEN & BROADWAY       -> 34 of 473
On Station BROOKLYN BRIDGE                -> 35 of 473
On Station 42ND STREET & GRAND CENTRAL    -> 36 of 473
On Station 42ND STREET & 3RD AVENUE       -> 37 of 473
On Station 51ST STREET & LEXINGTON AVE    -> 38 of 473
On Station 59TH STREET & LEXINGTON AVE    -> 39 of 473
On Station WOODLAWN ROAD                  -> 40 of 473
On Station 149TH STREET & 3RD AVENUE      -> 41 of 473
On Station FIFTH AVENUE & 42ND STREET     -> 42 of 473
On Station MAIN STREET                    -> 43 of 473
On Station NEVINS STREET                  -> 44 of 473
On Station BARCLAYS CENTER                -> 45 of 473
On Station BERGEN STREET                  -> 46 of 473
On Station GRAND ARMY PLAZA               -> 47 of 473
On Station EASTERN PARKWAY                -> 48 of 473
On Station NOSTRAND AVENUE                -> 49 of 473
On Station UTICA AVENUE                   -> 50 of 473
On Station SUTTER AVENUE                  -> 51 of 473
On Station SARATOGA AVENUE                -> 52 of 473
On Station ROCKAWAY AVENUE                -> 53 of 473
On Station JUNIUS STREET                  -> 54 of 473
On Station PENNSYLVANIA AVENUE            -> 55 of 473
On Station VAN SICLEN AVENUE              -> 56 of 473
On Station NEW LOTS AVENUE                -> 57 of 473
On Station ST GEORGE TERMINAL             -> 58 of 473
On Station 34TH STREET - HUDSON YARDS     -> 59 of 473
On Station FIFTH AVENUE & 60TH STREET     -> 60 of 473
On Station 57TH STREET & 7TH AVENUE       -> 61 of 473
On Station 49TH STREET & 7TH AVENUE       -> 62 of 473
On Station 28TH STREET & BROADWAY         -> 63 of 473
On Station 23RD STREET & 5TH AVENUE       -> 64 of 473
On Station 59TH STREET/COLUMBUS CIRCLE    -> 65 of 473
On Station 8TH STREET & BROADWAY          -> 66 of 473
On Station PRINCE STREET & BROADWAY       -> 67 of 473
On Station CITY HALL                      -> 68 of 473
On Station CORTLANDT STREET               -> 69 of 473
On Station JAY ST-METROTECH               -> 70 of 473
On Station 39TH AVENUE & 31ST STREET      -> 71 of 473
On Station 36TH AVENUE & 31ST STREET      -> 72 of 473
On Station BROADWAY & 31ST STREET         -> 73 of 473
On Station 30TH AVENUE & 31ST STREET      -> 74 of 473
On Station ASTORIA BLVD & 31ST STREET     -> 75 of 473
On Station DITMARS BLVD & 31ST STREET     -> 76 of 473
On Station 82ND STREET-JACKSON HEIGHTS    -> 77 of 473
On Station JUNCTION BLVD-ROOSEVELT AVE    -> 78 of 473
On Station CHURCH AVENUE                  -> 79 of 473
On Station DEKALB AVENUE                  -> 80 of 473
On Station METROPOLITAN AVENUE            -> 81 of 473
On Station 145TH STREET                   -> 82 of 473
On Station 125TH STREET                   -> 83 of 473
On Station BROADWAY-EAST NEW YORK         -> 84 of 473
On Station 167TH ST-GRAND CONCOURSE       -> 85 of 473
On Station 14TH STREET & 7TH AVENUE       -> 86 of 473
On Station CASTLE HILL AVENUE             -> 87 of 473
On Station WESTCHESTER SQUARE             -> 88 of 473
On Station BOROUGH HALL - COURT STREET    -> 89 of 473
On Station CHURCH AVENUE & NOSTRAND AV    -> 90 of 473
On Station FLATBUSH AVE & NOSTRAND AV     -> 91 of 473
On Station 23RD STREET & 8TH AVENUE       -> 92 of 473
On Station FORDHAM RD/GRAND CONCOURSE     -> 93 of 473
On Station SEVENTH AVENUE & WEST 53RD     -> 94 of 473
On Station PARSONS BLVD & HILLSIDE AV     -> 95 of 473
On Station 169TH STREET & HILLSIDE AVE    -> 96 of 473
On Station 50TH STREET & 7TH AVENUE       -> 97 of 473
On Station 242ND STREET & BROADWAY        -> 98 of 473
On Station CANAL STREET                   -> 99 of 473
On Station FORDHAM ROAD & JEROME AVE      -> 100 of 473
On Station MORRISON AVE & WESTCHESTER     -> 101 of 473
On Station QUEENSBORO PLAZA               -> 102 of 473
On Station 90TH STREET/ELMHURST AVENUE    -> 103 of 473
On Station FRANKLIN AVE/EASTERN PKWY      -> 104 of 473
On Station KINGSTON AVE/EASTERN PKWY      -> 105 of 473
On Station BROAD STREET & WALL STREET     -> 106 of 473
On Station 175TH STREET/FT WASHINGTON     -> 107 of 473
On Station SUTPHIN BLVD-HILLSIDE AVE      -> 108 of 473
On Station BERGEN STREET-SMITH STREET     -> 109 of 473
On Station KINGS HIGHWAY-MCDONALD AVE     -> 110 of 473
On Station 23RD STREET-PARK AVE SOUTH     -> 111 of 473
On Station 125TH STREET-LEXINGTON AVE     -> 112 of 473
On Station MOSHOLU PARKWAY-JEROME AVE     -> 113 of 473
On Station HUNTERS PT AVE-49TH AVE        -> 114 of 473
On Station NEWKIRK AVE-NOSTRAND AVE       -> 115 of 473
On Station SHEEPSHEAD BAY ROAD            -> 116 of 473
On Station MYRTLE AVE-GATES AVENUE        -> 117 of 473
On Station WEST 4TH ST-WASHINGTON SQ      -> 118 of 473
On Station CANAL STREET-LISPENARD ST      -> 119 of 473
On Station QUEENS PLAZA-JACKSON AVE       -> 120 of 473
On Station 71ST AVE-CONTINENTAL AVE       -> 121 of 473
On Station ESSEX ST-DELANCEY ST           -> 122 of 473
On Station 28TH STREET-PARK AVE SOUTH     -> 123 of 473
On Station 96TH STREET-LEXINGTON AVE      -> 124 of 473
On Station 241ST ST-WHITE PLAINS RD       -> 125 of 473
On Station HUNTS PT AVE-SOUTHERN BLVD     -> 126 of 473
On Station 61ST STREET-ROOSEVELT AVE      -> 127 of 473
On Station PARKSIDE AVE-OCEAN AVE         -> 128 of 473
On Station NEWKIRK PLAZA                  -> 129 of 473
On Station AVENUE U-EAST 16TH STREET      -> 130 of 473
On Station STILLWELL AVE-CONEY ISLAND     -> 131 of 473
On Station ROCKAWAY PKWY-GLENWOOD RD      -> 132 of 473
On Station UTICA AVE-STUYVESANT AVE       -> 133 of 473
On Station TREMONT AVE-179TH ST           -> 134 of 473
On Station KINGSBRIDGE RD-196TH ST        -> 135 of 473
On Station BEDFORD PARK BLVD-203RD ST     -> 136 of 473
On Station 205TH ST-BAINBRIDGE AVE        -> 137 of 473
On Station UNION TURNPIKE-KEW GARDENS     -> 138 of 473
On Station 116TH STREET-COLUMBIA          -> 139 of 473
On Station ASTOR PLACE-4 AVENUE           -> 140 of 473
On Station KINGSBRIDGE RD-JEROME AVE      -> 141 of 473
On Station ELDER AVE-WESTCHESTER AVE      -> 142 of 473
On Station 14TH STREET-6TH AVENUE         -> 143 of 473
On Station 66TH STREET-BROADWAY           -> 144 of 473
On Station TOMPKINSVILLE                  -> 145 of 473
On Station 79TH STREET-BROADWAY           -> 146 of 473
On Station 86TH STREET-BROADWAY           -> 147 of 473
On Station 96TH STREET-BROADWAY           -> 148 of 473
On Station 137TH STREET-BROADWAY          -> 149 of 473
On Station 14TH STREET-UNION SQUARE       -> 150 of 473
On Station 7TH AVENUE-PARK PLACE          -> 151 of 473
On Station BRIGHTON BEACH-CONEY ISLAND    -> 152 of 473
On Station 207TH STREET-BROADWAY          -> 153 of 473

On Station 181ST STREET-FT WASH AVE       -> 154 of 473
On Station 8TH AVENUE-14TH STREET         -> 155 of 473
On Station 33RD STREET-PARK AVENUE        -> 156 of 473
On Station 68TH STREET-HUNTER COLLEGE     -> 157 of 473
On Station 77TH STREET-LEXINGTON AVE      -> 158 of 473
On Station 86TH STREET-LEXINGTON AVE      -> 159 of 473
On Station 103RD STREET-LEXINGTON AVE     -> 160 of 473
On Station 110TH STREET-LEXINGTON AVE     -> 161 of 473
On Station 116TH STREET-LEXINGTON AVE     -> 162 of 473
On Station BEDFORD PARK BLVD-JEROME AV    -> 163 of 473
On Station CORTELYOU RD-EAST 16TH ST      -> 164 of 473
On Station DYCKMAN STREET-BROADWAY        -> 165 of 473
On Station 86TH ST-CENTRAL PARK WEST      -> 166 of 473
On Station 81ST STREET-MUSEUM             -> 167 of 473
On Station 50TH STREET-8TH AVENUE         -> 168 of 473
On Station CHRISTOPHER ST-SHERIDAN SQ     -> 169 of 473
On Station 23RD STREET-7TH AVENUE         -> 170 of 473
On Station 103RD STREET-BROADWAY          -> 171 of 473
On Station 110TH STREET-BROADWAY          -> 172 of 473
On Station 157TH STREET-BROADWAY          -> 173 of 473
On Station BLEECKER ST-LAFAYETTE ST       -> 174 of 473
On Station 161ST STREET-YANKEE STADIUM    -> 175 of 473
On Station PROSPECT PARK-EMPIRE BLVD      -> 176 of 473
On Station 36TH STREET-4TH AVENUE         -> 177 of 473
On Station NOSTRAND AVE-FULTON ST         -> 178 of 473
On Station KINGSTON AVE-THROOP AVE        -> 179 of 473
On Station EUCLID AVE-PITKIN AVE          -> 180 of 473
On Station WOODHAVEN BLVD-QUEENS BLVD     -> 181 of 473
On Station 63RD DRIVE-REGO PARK           -> 182 of 473
On Station 23RD STREET-6TH AVENUE         -> 183 of 473
On Station CHURCH AVE-MCDONALD AVE        -> 184 of 473
On Station 149TH ST-GRAND CONCOURSE       -> 185 of 473
On Station 125TH STREET-LENOX AVENUE      -> 186 of 473
On Station 135TH STREET-LENOX AVENUE      -> 187 of 473
On Station 103RD ST-ROOSEVELT AVE         -> 188 of 473
On Station STERLING ST-NOSTRAND AVE       -> 189 of 473
On Station BEVERLY RD-NOSTRAND AVE        -> 190 of 473
On Station KINGS HIGHWAY-EAST 16TH ST     -> 191 of 473
On Station 59TH STREET-4TH AVENUE         -> 192 of 473
On Station BAY RIDGE AVE-4TH AVENUE       -> 193 of 473
On Station 77TH STREET-4TH AVENUE         -> 194 of 473
On Station 86TH STREET-4TH AVENUE         -> 195 of 473
On Station BAY RIDGE - 95TH STREET        -> 196 of 473
On Station HOYT ST-SCHERMERHORN ST        -> 197 of 473
On Station ELMHURST AVE-BROADWAY          -> 198 of 473
On Station 67TH AVENUE-QUEENS BLVD        -> 199 of 473
On Station CARROLL ST-PRESIDENT ST        -> 200 of 473
On Station 167TH STREET-RIVER AVENUE      -> 201 of 473
On Station 177TH STREET-PARKCHESTER       -> 202 of 473
On Station 46TH ST-BLISS ST               -> 203 of 473
On Station HOYT STREET-HOYT STREET        -> 204 of 473
On Station GUN HILL ROAD-SEYMOUR          -> 205 of 473
On Station RECTOR STREET-CHURCH STREET    -> 206 of 473
On Station AVENUE J-EAST 16TH STREET      -> 207 of 473
On Station AVENUE M-EAST 16TH STREET      -> 208 of 473
On Station NECK ROAD-EAST 16TH STREET     -> 209 of 473
On Station UNION STREET-4TH AVENUE        -> 210 of 473
On Station 45TH STREET-4TH AVENUE         -> 211 of 473
On Station 53RD STREET-4TH AVENUE         -> 212 of 473
On Station 50TH STREET-NEW UTRECHT AVE    -> 213 of 473
On Station BEDFORD AVE-NORTH 7TH ST       -> 214 of 473
On Station DEKALB AVE-WYCKOFF AVE         -> 215 of 473
On Station 182ND STREET-183RD STREET      -> 216 of 473
On Station STEINWAY ST-BROADWAY           -> 217 of 473
On Station GREENPOINT AVE                 -> 218 of 473
On Station GRAND ST-CHRISTIE ST           -> 219 of 473
On Station 15TH ST-PROSPECT PARK WEST     -> 220 of 473
On Station 18TH AVE-MCDONALD AVE          -> 221 of 473
On Station 170TH STREET-JEROME AVENUE     -> 222 of 473
On Station BURNSIDE AVE-JEROME AVE        -> 223 of 473
On Station ST LAWRENCE AVE-WEST AVE       -> 224 of 473
On Station PROSPECT AVENUE-4TH AVENUE     -> 225 of 473
On Station 55TH ST-NEW UTRECHT AVE        -> 226 of 473
On Station 1ST AVENUE-14TH STREET         -> 227 of 473
On Station GRAHAM AVE-METROPOLITAN AVE    -> 228 of 473
On Station GRAND ST-BUSHWICK AVE          -> 229 of 473
On Station 96TH ST-CENTRAL PARK WEST      -> 230 of 473
On Station HIGH ST-CADMAN PLAZA WEST      -> 231 of 473
On Station 174TH-175TH ST-GRAND CONCOU    -> 232 of 473
On Station GRAND AVE-QUEENS BOULEVARD     -> 233 of 473
On Station VAN WYCK BLVD-MAIN STREET      -> 234 of 473
On Station NASSAU AVE-MANHATTAN AVE       -> 235 of 473
On Station EAST BROADWAY-MADISON ST       -> 236 of 473
On Station 4TH AVENUE-9TH STREET          -> 237 of 473
On Station ROOSEVELT ISLAND               -> 238 of 473
On Station 181ST STREET-ST NICHOLAS AV    -> 239 of 473
On Station 40TH STREET-LOWERY STREET      -> 240 of 473
On Station BEVERLEY ROAD -EAST 15TH ST    -> 241 of 473
On Station AVENUE H-EAST 16TH STREET      -> 242 of 473
On Station OCEAN PKWAY-BRIGHTON BCH AV    -> 243 of 473
On Station MONTROSE AVENUE                -> 244 of 473
On Station HALSEY STREET-WYCKOFF AVE      -> 245 of 473
On Station 46TH STREET-BROADWAY           -> 246 of 473
On Station METROPOLITAN AVE-LORIMER ST    -> 247 of 473
On Station BEDFORD AVENUE-NOSTRAND AVE    -> 248 of 473
On Station SMITH STREET-9TH STREET        -> 249 of 473
On Station AVENUE X-MCDONALD AVENUE       -> 250 of 473
On Station 28TH STREET-7TH AVENUE         -> 251 of 473
On Station 145TH STREET-BROADWAY          -> 252 of 473
On Station 191ST STREET-ST NICHOLAS AV    -> 253 of 473
On Station 183RD STREET-JEROME AVENUE     -> 254 of 473
On Station JACKSON AVENUE-VERNON BLVD     -> 255 of 473
On Station PRESIDENT ST-NOSTRAND AVE      -> 256 of 473
On Station 25TH STREET-4TH AVENUE         -> 257 of 473
On Station JEFFERSON STREET-WYCKOFF AV    -> 258 of 473
On Station 190TH STREET-OVERLOOK TERR     -> 259 of 473
On Station 72ND STREET-CENTRAL PK WEST    -> 260 of 473
On Station SPRING STREET-6TH AVENUE       -> 261 of 473
On Station LAFAYETTE AVENUE-FULTON ST     -> 262 of 473
On Station CLINTON AVENUE-FULTON ST       -> 263 of 473
On Station MOTT AVENUE-BEACH 22ND ST      -> 264 of 473
On Station MYRTLE AVENUE-MARCY AVENUE     -> 265 of 473
On Station CLASSON AVENUE-LAFAYETTE AV    -> 266 of 473
On Station 7TH AVENUE-9TH STREET          -> 267 of 473
On Station FT HAMILTON PKY-GREENWOOD      -> 268 of 473
On Station HOUSTON STREET-VARICK ST       -> 269 of 473
On Station 33RD STREET-QUEENS BLVD        -> 270 of 473
On Station BAYCHESTER AVE-TILLOTSON       -> 271 of 473
On Station 34TH STREET - PENN STATION     -> 272 of 473
On Station MORGAN AVENUE-HARRISON PL      -> 273 of 473
On Station WILSON AVENUE-MOFFAT STREET    -> 274 of 473
On Station 163RD ST & AMSTERDAM AVE       -> 275 of 473
On Station FRANKLIN AVENUE-FULTON ST      -> 276 of 473
On Station NORTHERN BLVD-BROADWAY         -> 277 of 473
On Station BROADWAY - UNION AVENUE        -> 278 of 473
On Station 2ND AVENUE-HOUSTON STREET      -> 279 of 473
On Station YORK STREET-JAY STREET         -> 280 of 473
On Station 57TH STREET-6TH AVENUE         -> 281 of 473
On Station 21ST STREET-QUEENSBRIDGE       -> 282 of 473
On Station RECTOR STREET-GREENWICH ST     -> 283 of 473
On Station WTC-CORTLANDT ST               -> 284 of 473
On Station 238TH STREET-BROADWAY          -> 285 of 473
On Station 138TH ST-GRAND CONCOURSE       -> 286 of 473
On Station MT EDEN AVENUE-JEROME AVE      -> 287 of 473
On Station 176TH STREET-JEROME AVENUE     -> 288 of 473
On Station 111TH STREET-ROOSEVELT AVE     -> 289 of 473
On Station BOWERY STREET-DELANCEY ST      -> 290 of 473
On Station WEST 6TH STREET-SURF AVENUE    -> 291 of 473
On Station BUSHWICK AVENUE-ABERDEEN ST    -> 292 of 473
On Station 103RD ST-CENTRAL PARK WEST     -> 293 of 473
On Station 155TH STREET-8TH AVENUE        -> 294 of 473
On Station FLUSHING AVENUE-MARCY AVE      -> 295 of 473
On Station LAFAYETTE AV-WASHINGTON AV     -> 296 of 473
On Station FULTON STREET-LAFAYETTE AV     -> 297 of 473
On Station 63RD STREET-LEXINGTON AVE      -> 298 of 473
On Station CANAL STREET-VARICK STREET     -> 299 of 473
On Station 18TH STREET-7TH AVENUE         -> 300 of 473
On Station SPRING STREET-LAFAYETTE ST     -> 301 of 473
On Station 111TH STREET-LENOX AVENUE      -> 302 of 473
On Station 116TH STREET-LENOX AVENUE      -> 303 of 473
On Station WHITLOCK AVE-WESTCHESTER AV    -> 304 of 473
On Station ZEREGA AVE-WESTCHESTER AVE     -> 305 of 473
On Station 52ND STREET-ROOSEVELT AVE      -> 306 of 473
On Station WILLETS PT BLVD-ROOSEVELT      -> 307 of 473
On Station MORRIS PARK-PAULDING AVENUE    -> 308 of 473
On Station 3RD AVENUE-14TH STREET         -> 309 of 473
On Station 155TH STREET-ST NICHOLAS AV    -> 310 of 473
On Station 135TH STREET-ST NICHOLAS AV    -> 311 of 473
On Station 116TH STREET-8TH AVENUE        -> 312 of 473
On Station 110TH STREET-8TH AVENUE        -> 313 of 473
On Station GASTON AVENUE-BEACH 67TH ST    -> 314 of 473
On Station STRAITON AVE-BEACH 60TH ST     -> 315 of 473
On Station FRANK AVENUE-BEACH 44TH ST     -> 316 of 473
On Station EDGEMERE-BEACH 36TH STREET     -> 317 of 473
On Station 36TH STREET-NORTHERN BLVD      -> 318 of 473
On Station 65TH STREET-BROADWAY           -> 319 of 473
On Station 75TH AVENUE-QUEENS BLVD        -> 320 of 473
On Station VAN WYCK BLVD-METROPOLITAN     -> 321 of 473
On Station FRANKLIN STREET-WEST BWAY      -> 322 of 473
On Station 145TH STREET-LENOX AVENUE      -> 323 of 473
On Station 148TH STREET-LENOX AVENUE      -> 324 of 473
On Station COURT SQ                       -> 325 of 473
On Station 69TH STREET-ROOSEVELT AVE      -> 326 of 473
On Station ATLANTIC AV-VAN SINDEREN AV    -> 327 of 473
On Station SUTTER AVE-VAN SINDEREN AVE    -> 328 of 473
On Station LIVONIA AVE-VAN SINDEREN AV    -> 329 of 473
On Station HEWES STREET-BROADWAY          -> 330 of 473
On Station LORIMER STREET-BROADWAY        -> 331 of 473
On Station 104TH STREET-LIBERTY AVENUE    -> 332 of 473
On Station 109TH STREET-LIBERTY AVENUE    -> 333 of 473
On Station LEFFERTS BLVD-LIBERTY AVE      -> 334 of 473
On Station NORTH CONDUIT AVE-COHANCEY     -> 335 of 473
On Station BEACH 25TH STREET-WAVECREST    -> 336 of 473
On Station COURT SQ-23 ST                 -> 337 of 473
On Station 21ST STREET-JACKSON AVENUE     -> 338 of 473
On Station PELHAM PKWY-WHITE PLAINS RD    -> 339 of 473
On Station ALLERTON AV-WHITE PLAINS RD    -> 340 of 473
On Station BURKE AVE-WHITE PLAINS ROAD    -> 341 of 473
On Station GUNHILL RD-WHITE PLAINS RD     -> 342 of 473
On Station 219TH ST-WHITE PLAINS ROAD     -> 343 of 473
On Station 225TH ST-WHITE PLAINS ROAD     -> 344 of 473
On Station 233RD ST-WHITE PLAINS ROAD     -> 345 of 473
On Station 9TH AVENUE-39TH STREET         -> 346 of 473
On Station FORT HAMILTON PKWY-45TH ST     -> 347 of 473
On Station 71ST STREET-NEW UTRECHT AVE    -> 348 of 473
On Station 79TH STREET-17TH AVENUE        -> 349 of 473
On Station 18TH AVENUE-86TH STREET        -> 350 of 473
On Station 20TH AVENUE-86TH STREET        -> 351 of 473
On Station BAY PARKWAY-86TH STREET        -> 352 of 473
On Station NEW LOTS AV-VAN SINDEREN AV    -> 353 of 473
On Station EAST 105TH ST-FARRAGUT ROAD    -> 354 of 473
On Station FLUSHING AVE-BROADWAY          -> 355 of 473
On Station MYRTLE AVENUE-BROADWAY         -> 356 of 473
On Station KOSCIUSZKO STREET-BROADWAY     -> 357 of 473
On Station GATES AVENUE-BROADWAY          -> 358 of 473
On Station HALSEY STREET-BROADWAY         -> 359 of 473
On Station GRANT AVENUE-PITKIN AVENUE     -> 360 of 473
On Station HUDSON STREET-78TH STREET      -> 361 of 473
On Station BOYD STREET-88TH STREET        -> 362 of 473
On Station ROCKAWAY BLVD-LIBERTY AVE      -> 363 of 473

On Station 174TH STREET-SOUTHERN BLVD     -> 364 of 473
On Station EAST TREMONT AVENUE-178 ST     -> 365 of 473
On Station EAST 180TH ST-MORRIS PARK      -> 366 of 473
On Station BRONX PARK EAST                -> 367 of 473
On Station 8TH AVENUE-62ND STREET         -> 368 of 473
On Station FORT HAMILTON PARKWAY-62ND     -> 369 of 473
On Station 18TH AVENUE-62ND STREET        -> 370 of 473
On Station 20TH AVENUE-62ND STREET        -> 371 of 473
On Station BAY PARKWAY-66TH STREET        -> 372 of 473
On Station KINGS HIGHWAY-WEST 7TH ST      -> 373 of 473
On Station AVENUE U-WEST 7TH STREET       -> 374 of 473
On Station 86TH STREET-AVENUE V           -> 375 of 473
On Station NEW UTRECHT AVENUE-62ND ST     -> 376 of 473
On Station 25TH AVENUE-86TH STREET        -> 377 of 473
On Station BAY 50TH STREET-STILLWELL      -> 378 of 473
On Station CENTRAL AVE-MYRTLE AVE         -> 379 of 473
On Station SENECA AVENUE-PALMETTO ST      -> 380 of 473
On Station FOREST AVENUE-PUTNAM AVENUE    -> 381 of 473
On Station FRESH POND ROAD-68TH AVENUE    -> 382 of 473
On Station JACKSON AVENUE-WESTCHESTER     -> 383 of 473
On Station PROSPECT AVENUE-WESTCHESTER    -> 384 of 473
On Station INTERVALE 163RD STREET         -> 385 of 473
On Station SIMPSON ST-WESTCHESTER AVE     -> 386 of 473
On Station FREEMAN ST-SOUTHERN BLVD       -> 387 of 473
On Station PARK PLACE-FRANKLIN AVENUE     -> 388 of 473
On Station BOTANIC GARDEN-FRANKLIN AVE    -> 389 of 473
On Station KNICKERBOCKER AVE-MYRTLE AV    -> 390 of 473
On Station HOWARD BEACH-159TH AVE         -> 391 of 473
On Station BROAD CHANNEL-NOEL ROAD        -> 392 of 473
On Station HOLLAND-BEACH 90TH STREET      -> 393 of 473
On Station PLAYLAND-BEACH 98TH STREET     -> 394 of 473
On Station SEASIDE BEACH-105TH STREET     -> 395 of 473
On Station ROCKAWAY PARK-BEACH 116TH      -> 396 of 473
On Station DITMAS AVE-MCDONALD AVE        -> 397 of 473
On Station AVENUE I-MCDONALD AVENUE       -> 398 of 473
On Station MCDONALD AVE-22ND AVE          -> 399 of 473
On Station AVENUE N-MCDONALD AVENUE       -> 400 of 473
On Station AVENUE P-MCDONALD AVENUE       -> 401 of 473
On Station AVENUE U-MCDONALD AVENUE       -> 402 of 473
On Station NEPTUNE AVE-MCDONALD AVENUE    -> 403 of 473
On Station MIDDLETOWN ROAD-WESTCHESTER    -> 404 of 473
On Station BUHRE AVE-WESTCHESTER AVE      -> 405 of 473
On Station PELHAM BAY PARK-BRUCKNER BL    -> 406 of 473
On Station PELHAM PKWY-ESPLANADE          -> 407 of 473
On Station DYRE AVENUE-LIGHT STREET       -> 408 of 473
On Station CHAUNCEY STREET-ROCKAWAY AV    -> 409 of 473
On Station ALABAMA AVENUE-FULTON ST       -> 410 of 473
On Station VAN SICLEN AVENUE-FULTON ST    -> 411 of 473
On Station CLEVELAND STREET-FULTON ST     -> 412 of 473
On Station NORWOOD AVENUE-FULTON ST       -> 413 of 473
On Station CRESCENT STREET-FULTON ST      -> 414 of 473
On Station RALPH AVENUE-FULTON STREET     -> 415 of 473
On Station ROCKAWAY AVE-HOPKINSON AVE     -> 416 of 473
On Station LIBERTY AVE-PENNSYLVANIA AV    -> 417 of 473
On Station VAN SICLEN AVE-PITKIN AVE      -> 418 of 473
On Station SHEPHERD AVE-PITKIN AVE        -> 419 of 473
On Station 170TH STREET-GRAND CONC.       -> 420 of 473
On Station 238TH ST-WHITE PLAINS ROAD     -> 421 of 473
On Station 138TH STREET-3RD AVE           -> 422 of 473
On Station BROOK AVENUE-138TH STREET      -> 423 of 473
On Station CYPRESS AVENUE-138TH STREET    -> 424 of 473
On Station EAST 143RD ST-SOUTHERN BLVD    -> 425 of 473
On Station EAST 149TH ST-SOUTHERN BLVD    -> 426 of 473
On Station LONGWOOD AVE-SOUTHERN BLVD     -> 427 of 473
On Station WINTHROP ST-NOSTRAND AVE       -> 428 of 473
On Station 72ND STREET & BROADWAY         -> 429 of 473
On Station HOYT STREET-FULTON STREET      -> 430 of 473
On Station MARCY AVENUE-BROADWAY          -> 431 of 473
On Station BROADWAY LAFAYETTE-BLEECKER    -> 432 of 473
On Station CANAL STREET-BROADWAY          -> 433 of 473
On Station CANAL ST-LAFAYETTE ST EAST     -> 434 of 473
On Station AQUEDUCT RACE TRACK            -> 435 of 473
On Station RI TRAMWAY (MANHATTAN)         -> 436 of 473
On Station RI TRAMWAY (ROOSEVELT)         -> 437 of 473
On Station AIRTRAIN @ HOWARD BEACH        -> 438 of 473
On Station AIRTRAIN JAMAICA CENTER 1      -> 439 of 473
On Station PA-PATH WORLD TRADE CNTR       -> 440 of 473
On Station PA-PATH THIRTY THIRD ST        -> 441 of 473
On Station PA-PATH TWENTY THIRD ST        -> 442 of 473
On Station PA-PATH EXCHANGE PLACE         -> 443 of 473
On Station PA-PATH HARRISON               -> 444 of 473
On Station PA-PATH 14TH STREET            -> 445 of 473
On Station PA-PATH PAVONIA/NEWPORT        -> 446 of 473
On Station PA-PATH 9TH STREET             -> 447 of 473
On Station PA-PATH CHRISTOPHER ST         -> 448 of 473
On Station PA-PATH NEWARK                 -> 449 of 473
On Station PA-PATH HOBOKEN                -> 450 of 473
On Station PA-PATH GROVE ST               -> 451 of 473
On Station PA-PATH JOURNAL SQUARE         -> 452 of 473
On Station 72ND STREET - 2 AVENUE         -> 453 of 473
On Station 86TH STREET - 2 AVENUE         -> 454 of 473
On Station 96TH STREET - 2 AVENUE         -> 455 of 473
On Station SBS-M15 @ LIVINGSTON PLAZA     -> 456 of 473
On Station SBS-BX12 @ LIVINGSTON PLAZA    -> 457 of 473
On Station SBS-M34 @ LIVINGSTON PLAZA     -> 458 of 473
On Station SBS-BX41 @ LIVINGSTON PLAZA    -> 459 of 473
On Station SBS-B44 @ LIVINGSTON PLAZA     -> 460 of 473
On Station SBS-M60 @ LIVINGSTON PLAZA     -> 461 of 473
On Station SBS-M86 @ LIVINGSTON PLAZA     -> 462 of 473
On Station MTABC - EASTCHESTER 2          -> 463 of 473
On Station SBS-B46 @ LIVINGSTON PLAZA     -> 464 of 473
On Station SBS-Q44 @ LIVINGSTON PLAZA     -> 465 of 473
On Station SBS-BX6 @ LIVINGSTON PLAZA     -> 466 of 473
On Station SBS-Q52/53 @ LIVINGSTON PLAZA  -> 467 of 473
On Station SBS-B82 @ LIVINGSTON PLAZA     -> 468 of 473
On Station SBS-M14 @ LIVINGSTON PLAZA     -> 469 of 473
On Station SBS-M23 @ LIVINGSTON PLAZA     -> 470 of 473
On Station SBS-M79 @ LIVINGSTON PLAZA     -> 471 of 473
On Station CLARK STREET-HENRY STREET      -> 472 of 473

In [48]:
print(f"On Station {station} -> {stations22.index(station)} of {len(stations22)}")

On Station CLARK STREET-HENRY STREET

In [44]:
total22_by_months[stations22[0]]["february"]["total_card_swiped"]

174900

In [45]:
total22_by_months[stations22[0]]

{'january': {'total_card_swiped': 175529},
 'february': {'total_card_swiped': 174900},
 'march': {'total_card_swiped': 220189},
 'april': {'total_card_swiped': 242335}}

In [67]:
total22_by_months

{'WHITEHALL STREET              ': {'january': {'total_card_swiped': 175529},
  'february': {'total_card_swiped': 174900},
  'march': {'total_card_swiped': 220189},
  'april': {'total_card_swiped': 242335}},
 'CYPRESS HILLS                 ': {'january': {'total_card_swiped': 18595},
  'february': {'total_card_swiped': 13222},
  'march': {'total_card_swiped': 16717},
  'april': {'total_card_swiped': 16435}},
 '75TH STREET & ELDERTS LANE    ': {'january': {'total_card_swiped': 53080},
  'february': {'total_card_swiped': 35939},
  'march': {'total_card_swiped': 44399},
  'april': {'total_card_swiped': 43647}},
 '85TH STREET & FOREST PKWAY    ': {'january': {'total_card_swiped': 52242},
  'february': {'total_card_swiped': 36381},
  'march': {'total_card_swiped': 45203},
  'april': {'total_card_swiped': 44539}},
 'WOODHAVEN BOULEVARD           ': {'january': {'total_card_swiped': 53070},
  'february': {'total_card_swiped': 39100},
  'march': {'total_card_swiped': 49467},
  'april': {'total_card_swiped': 51301}},
 '104TH STREET                  ': {'january': {'total_card_swiped': 37951},
  'february': {'total_card_swiped': 27951},
  'march': {'total_card_swiped': 34624},
  'april': {'total_card_swiped': 34115}},
 '111TH STREET                  ': {'january': {'total_card_swiped': 30586},
  'february': {'total_card_swiped': 22152},
  'march': {'total_card_swiped': 27774},
  'april': {'total_card_swiped': 27292}},
 '121ST STREET                  ': {'january': {'total_card_swiped': 26389},
  'february': {'total_card_swiped': 18968},
  'march': {'total_card_swiped': 22722},
  'april': {'total_card_swiped': 23602}},
 '42ND STREET & 8TH AVENUE      ': {'january': {'total_card_swiped': 891179},
  'february': {'total_card_swiped': 798974},
  'march': {'total_card_swiped': 918875},
  'april': {'total_card_swiped': 920991}},
 '34TH STREET & 8TH AVENUE      ': {'january': {'total_card_swiped': 595660},
  'february': {'total_card_swiped': 523333},
  'march': {'total_card_swiped': 664754},
  'april': {'total_card_swiped': 666081}},
 'FULTON STREET                 ': {'january': {'total_card_swiped': 437745},
  'february': {'total_card_swiped': 439440},
  'march': {'total_card_swiped': 473898},
  'april': {'total_card_swiped': 493338}},
 'FIFTH AVENUE                  ': {'january': {'total_card_swiped': 155285},
  'february': {'total_card_swiped': 132485},
  'march': {'total_card_swiped': 173520},
  'april': {'total_card_swiped': 174950}},
 'LEXINGTON AVENUE              ': {'january': {'total_card_swiped': 293204},
  'february': {'total_card_swiped': 261515},
  'march': {'total_card_swiped': 313487},
  'april': {'total_card_swiped': 308907}},
 'ROOSEVELT AVE/JACKSON HTS     ': {'january': {'total_card_swiped': 650220},
  'february': {'total_card_swiped': 577827},
  'march': {'total_card_swiped': 620245},
  'april': {'total_card_swiped': 610382}},
 '179TH STREET & HILLSIDE AVE   ': {'january': {'total_card_swiped': 176871},
  'february': {'total_card_swiped': 159333},
  'march': {'total_card_swiped': 167251},
  'april': {'total_card_swiped': 159170}},
 '47-50 STREETS/ROCKEFELLER     ': {'january': {'total_card_swiped': 419633},
  'february': {'total_card_swiped': 414904},
  'march': {'total_card_swiped': 442992},
  'april': {'total_card_swiped': 456500}},
 '42ND STREET & 6TH AVENUE      ': {'january': {'total_card_swiped': 267217},
  'february': {'total_card_swiped': 276868},
  'march': {'total_card_swiped': 290587},
  'april': {'total_card_swiped': 305127}},
 '34TH STREET & 6TH AVENUE      ': {'january': {'total_card_swiped': 936823},
  'february': {'total_card_swiped': 927280},
  'march': {'total_card_swiped': 970572},
  'april': {'total_card_swiped': 996464}},
 'SUTPHIN BOULEVARD             ': {'january': {'total_card_swiped': 257204},
  'february': {'total_card_swiped': 223391},
  'march': {'total_card_swiped': 252047},
  'april': {'total_card_swiped': 257051}},
 'JAMAICA CENTER-PARSONS BLVD   ': {'january': {'total_card_swiped': 250286},
  'february': {'total_card_swiped': 219629},
  'march': {'total_card_swiped': 236326},
  'april': {'total_card_swiped': 229389}},
 'WALL STREET                   ': {'january': {'total_card_swiped': 230931},
  'february': {'total_card_swiped': 231073},
  'march': {'total_card_swiped': 246080},
  'april': {'total_card_swiped': 255630}},
 'FULTON & WILLIAM STREETS      ': {'january': {'total_card_swiped': 205831},
  'february': {'total_card_swiped': 197265},
  'march': {'total_card_swiped': 213706},
  'april': {'total_card_swiped': 214743}},
 'PARK PLACE                    ': {'january': {'total_card_swiped': 329144},
  'february': {'total_card_swiped': 309909},
  'march': {'total_card_swiped': 366550},
  'april': {'total_card_swiped': 368244}},
 'CHAMBERS STREET               ': {'january': {'total_card_swiped': 162036},
  'february': {'total_card_swiped': 164804},
  'march': {'total_card_swiped': 177502},
  'april': {'total_card_swiped': 163426}},
 '34TH STREET & 7TH AVENUE      ': {'january': {'total_card_swiped': 209162},
  'february': {'total_card_swiped': 207193},
  'march': {'total_card_swiped': 222433},
  'april': {'total_card_swiped': 227962}},
 '42ND STREET/TIMES SQUARE      ': {'january': {'total_card_swiped': 719215},
  'february': {'total_card_swiped': 712866},
  'march': {'total_card_swiped': 776137},
  'april': {'total_card_swiped': 828920}},
 '125TH STREET & BROADWAY       ': {'january': {'total_card_swiped': 81282},
  'february': {'total_card_swiped': 77434},
  'march': {'total_card_swiped': 80846},
  'april': {'total_card_swiped': 77024}},
 '168TH STREET & BROADWAY       ': {'january': {'total_card_swiped': 258109},
  'february': {'total_card_swiped': 238221},
  'march': {'total_card_swiped': 246374},
  'april': {'total_card_swiped': 233202}},
 'DYCKMAN STREET                ': {'january': {'total_card_swiped': 96781},
  'february': {'total_card_swiped': 86768},
  'march': {'total_card_swiped': 92586},
  'april': {'total_card_swiped': 86431}},
 '207TH STREET                  ': {'january': {'total_card_swiped': 74497},
  'february': {'total_card_swiped': 68028},
  'march': {'total_card_swiped': 74022},
  'april': {'total_card_swiped': 70039}},
 '215TH STREET                  ': {'january': {'total_card_swiped': 22191},
  'february': {'total_card_swiped': 20808},
  'march': {'total_card_swiped': 22390},
  'april': {'total_card_swiped': 21016}},
 '225TH STREET                  ': {'january': {'total_card_swiped': 60901},
  'february': {'total_card_swiped': 55552},
  'march': {'total_card_swiped': 59686},
  'april': {'total_card_swiped': 56454}},
 '231ST STREET                  ': {'january': {'total_card_swiped': 101876},
  'february': {'total_card_swiped': 93166},
  'march': {'total_card_swiped': 98783},
  'april': {'total_card_swiped': 93616}},
 'BOWLING GREEN & BATTERY PL    ': {'january': {'total_card_swiped': 133894},
  'february': {'total_card_swiped': 129880},
  'march': {'total_card_swiped': 142027},
  'april': {'total_card_swiped': 149158}},
 'BOWLING GREEN & BROADWAY      ': {'january': {'total_card_swiped': 29697},
  'february': {'total_card_swiped': 28326},
  'march': {'total_card_swiped': 33285},
  'april': {'total_card_swiped': 39701}},
 'BROOKLYN BRIDGE               ': {'january': {'total_card_swiped': 241800},
  'february': {'total_card_swiped': 235514},
  'march': {'total_card_swiped': 259443},
  'april': {'total_card_swiped': 264370}},
 '42ND STREET & GRAND CENTRAL   ': {'january': {'total_card_swiped': 841094},
  'february': {'total_card_swiped': 831624},
  'march': {'total_card_swiped': 929632},
  'april': {'total_card_swiped': 965820}},
 '42ND STREET & 3RD AVENUE      ': {'january': {'total_card_swiped': 75534},
  'february': {'total_card_swiped': 73053},
  'march': {'total_card_swiped': 70261},
  'april': {'total_card_swiped': 77020}},
 '51ST STREET & LEXINGTON AVE   ': {'january': {'total_card_swiped': 125044},
  'february': {'total_card_swiped': 127195},
  'march': {'total_card_swiped': 135816},
  'april': {'total_card_swiped': 143094}},
 '59TH STREET & LEXINGTON AVE   ': {'january': {'total_card_swiped': 454133},
  'february': {'total_card_swiped': 420507},
  'march': {'total_card_swiped': 442704},
  'april': {'total_card_swiped': 440802}},
 'WOODLAWN ROAD                 ': {'january': {'total_card_swiped': 54476},
  'february': {'total_card_swiped': 49238},
  'march': {'total_card_swiped': 51506},
  'april': {'total_card_swiped': 50592}},
 '149TH STREET & 3RD AVENUE     ': {'january': {'total_card_swiped': 201650},
  'february': {'total_card_swiped': 179839},
  'march': {'total_card_swiped': 194311},
  'april': {'total_card_swiped': 187313}},
 'FIFTH AVENUE & 42ND STREET    ': {'january': {'total_card_swiped': 104148},
  'february': {'total_card_swiped': 99125},
  'march': {'total_card_swiped': 96810},
  'april': {'total_card_swiped': 109930}},
 'MAIN STREET                   ': {'january': {'total_card_swiped': 543609},
  'february': {'total_card_swiped': 495244},
  'march': {'total_card_swiped': 502768},
  'april': {'total_card_swiped': 510763}},
 'NEVINS STREET                 ': {'january': {'total_card_swiped': 91942},
  'february': {'total_card_swiped': 83602},
  'march': {'total_card_swiped': 85497},
  'april': {'total_card_swiped': 86837}},
 'BARCLAYS CENTER               ': {'january': {'total_card_swiped': 454881},
  'february': {'total_card_swiped': 419512},
  'march': {'total_card_swiped': 455732},
  'april': {'total_card_swiped': 422962}},
 'BERGEN STREET                 ': {'january': {'total_card_swiped': 35427},
  'february': {'total_card_swiped': 31499},
  'march': {'total_card_swiped': 34196},
  'april': {'total_card_swiped': 31842}},
 'GRAND ARMY PLAZA              ': {'january': {'total_card_swiped': 70536},
  'february': {'total_card_swiped': 64192},
  'march': {'total_card_swiped': 67757},
  'april': {'total_card_swiped': 65150}},
 'EASTERN PARKWAY               ': {'january': {'total_card_swiped': 46366},
  'february': {'total_card_swiped': 42826},
  'march': {'total_card_swiped': 41430},
  'april': {'total_card_swiped': 45767}},
 'NOSTRAND AVENUE               ': {'january': {'total_card_swiped': 41456},
  'february': {'total_card_swiped': 39767},
  'march': {'total_card_swiped': 40225},
  'april': {'total_card_swiped': 37059}},
 'UTICA AVENUE                  ': {'january': {'total_card_swiped': 257353},
  'february': {'total_card_swiped': 230095},
  'march': {'total_card_swiped': 238176},
  'april': {'total_card_swiped': 236445}},
 'SUTTER AVENUE                 ': {'january': {'total_card_swiped': 76361},
  'february': {'total_card_swiped': 67908},
  'march': {'total_card_swiped': 73073},
  'april': {'total_card_swiped': 65903}},
 'SARATOGA AVENUE               ': {'january': {'total_card_swiped': 63495},
  'february': {'total_card_swiped': 55910},
  'march': {'total_card_swiped': 58196},
  'april': {'total_card_swiped': 53702}},
 'ROCKAWAY AVENUE               ': {'january': {'total_card_swiped': 56701},
  'february': {'total_card_swiped': 47897},
  'march': {'total_card_swiped': 51329},
  'april': {'total_card_swiped': 47718}},
 'JUNIUS STREET                 ': {'january': {'total_card_swiped': 25176},
  'february': {'total_card_swiped': 22280},
  'march': {'total_card_swiped': 24253},
  'april': {'total_card_swiped': 22034}},
 'PENNSYLVANIA AVENUE           ': {'january': {'total_card_swiped': 50403},
  'february': {'total_card_swiped': 44385},
  'march': {'total_card_swiped': 48116},
  'april': {'total_card_swiped': 44192}},
 'VAN SICLEN AVENUE             ': {'january': {'total_card_swiped': 30544},
  'february': {'total_card_swiped': 27259},
  'march': {'total_card_swiped': 29036},
  'april': {'total_card_swiped': 26637}},
 'NEW LOTS AVENUE               ': {'january': {'total_card_swiped': 56971},
  'february': {'total_card_swiped': 50230},
  'march': {'total_card_swiped': 52781},
  'april': {'total_card_swiped': 49648}},
 'ST GEORGE TERMINAL            ': {'january': {'total_card_swiped': 75378},
  'february': {'total_card_swiped': 73107},
  'march': {'total_card_swiped': 80936},
  'april': {'total_card_swiped': 74345}},
 '34TH STREET - HUDSON YARDS    ': {'january': {'total_card_swiped': 172430},
  'february': {'total_card_swiped': 166641},
  'march': {'total_card_swiped': 148867},
  'april': {'total_card_swiped': 203210}},
 'FIFTH AVENUE & 60TH STREET    ': {'january': {'total_card_swiped': 132869},
  'february': {'total_card_swiped': 125365},
  'march': {'total_card_swiped': 140146},
  'april': {'total_card_swiped': 149353}},
 '57TH STREET & 7TH AVENUE      ': {'january': {'total_card_swiped': 276588},
  'february': {'total_card_swiped': 276392},
  'march': {'total_card_swiped': 301324},
  'april': {'total_card_swiped': 297754}},
 '49TH STREET & 7TH AVENUE      ': {'january': {'total_card_swiped': 183353},
  'february': {'total_card_swiped': 192382},
  'march': {'total_card_swiped': 217123},
  'april': {'total_card_swiped': 223732}},
 '28TH STREET & BROADWAY        ': {'january': {'total_card_swiped': 80035},
  'february': {'total_card_swiped': 82610},
  'march': {'total_card_swiped': 90909},
  'april': {'total_card_swiped': 92554}},
 '23RD STREET & 5TH AVENUE      ': {'january': {'total_card_swiped': 141756},
  'february': {'total_card_swiped': 148537},
  'march': {'total_card_swiped': 167422},
  'april': {'total_card_swiped': 171687}},
 '59TH STREET/COLUMBUS CIRCLE   ': {'january': {'total_card_swiped': 611184},
  'february': {'total_card_swiped': 613056},
  'march': {'total_card_swiped': 657686},
  'april': {'total_card_swiped': 653452}},
 '8TH STREET & BROADWAY         ': {'january': {'total_card_swiped': 110377},
  'february': {'total_card_swiped': 131106},
  'march': {'total_card_swiped': 137499},
  'april': {'total_card_swiped': 136585}},
 'PRINCE STREET & BROADWAY      ': {'january': {'total_card_swiped': 91928},
  'february': {'total_card_swiped': 97920},
  'march': {'total_card_swiped': 107083},
  'april': {'total_card_swiped': 110885}},
 'CITY HALL                     ': {'january': {'total_card_swiped': 43769},
  'february': {'total_card_swiped': 40259},
  'march': {'total_card_swiped': 49658},
  'april': {'total_card_swiped': 48609}},
 'CORTLANDT STREET              ': {'january': {'total_card_swiped': 115163},
  'february': {'total_card_swiped': 107110},
  'march': {'total_card_swiped': 146333},
  'april': {'total_card_swiped': 150216}},
 'JAY ST-METROTECH              ': {'january': {'total_card_swiped': 307969},
  'february': {'total_card_swiped': 309443},
  'march': {'total_card_swiped': 322612},
  'april': {'total_card_swiped': 309032}},
 '39TH AVENUE & 31ST STREET     ': {'january': {'total_card_swiped': 29901},
  'february': {'total_card_swiped': 28402},
  'march': {'total_card_swiped': 30214},
  'april': {'total_card_swiped': 26028}},
 '36TH AVENUE & 31ST STREET     ': {'january': {'total_card_swiped': 76177},
  'february': {'total_card_swiped': 70982},
  'march': {'total_card_swiped': 73029},
  'april': {'total_card_swiped': 62777}},
 'BROADWAY & 31ST STREET        ': {'january': {'total_card_swiped': 131901},
  'february': {'total_card_swiped': 123447},
  'march': {'total_card_swiped': 125069},
  'april': {'total_card_swiped': 108520}},
 '30TH AVENUE & 31ST STREET     ': {'january': {'total_card_swiped': 142673},
  'february': {'total_card_swiped': 130990},
  'march': {'total_card_swiped': 133232},
  'april': {'total_card_swiped': 116469}},
 'ASTORIA BLVD & 31ST STREET    ': {'january': {'total_card_swiped': 101772},
  'february': {'total_card_swiped': 96904},
  'march': {'total_card_swiped': 105434},
  'april': {'total_card_swiped': 106218}},
 'DITMARS BLVD & 31ST STREET    ': {'january': {'total_card_swiped': 158753},
  'february': {'total_card_swiped': 148464},
  'march': {'total_card_swiped': 154262},
  'april': {'total_card_swiped': 146518}},
 '82ND STREET-JACKSON HEIGHTS   ': {'january': {'total_card_swiped': 236237},
  'february': {'total_card_swiped': 212265},
  'march': {'total_card_swiped': 214802},
  'april': {'total_card_swiped': 211709}},
 'JUNCTION BLVD-ROOSEVELT AVE   ': {'january': {'total_card_swiped': 356208},
  'february': {'total_card_swiped': 306448},
  'march': {'total_card_swiped': 321135},
  'april': {'total_card_swiped': 323906}},
 'CHURCH AVENUE                 ': {'january': {'total_card_swiped': 175459},
  'february': {'total_card_swiped': 162903},
  'march': {'total_card_swiped': 169985},
  'april': {'total_card_swiped': 162749}},
 'DEKALB AVENUE                 ': {'january': {'total_card_swiped': 196844},
  'february': {'total_card_swiped': 185764},
  'march': {'total_card_swiped': 199543},
  'april': {'total_card_swiped': 183234}},
 'METROPOLITAN AVENUE           ': {'january': {'total_card_swiped': 41393},
  'february': {'total_card_swiped': 36219},
  'march': {'total_card_swiped': 39172},
  'april': {'total_card_swiped': 35778}},
 '145TH STREET                  ': {'january': {'total_card_swiped': 244124},
  'february': {'total_card_swiped': 235498},
  'march': {'total_card_swiped': 242496},
  'april': {'total_card_swiped': 230941}},
 '125TH STREET                  ': {'january': {'total_card_swiped': 279139},
  'february': {'total_card_swiped': 258813},
  'march': {'total_card_swiped': 275421},
  'april': {'total_card_swiped': 268289}},
 'BROADWAY-EAST NEW YORK        ': {'january': {'total_card_swiped': 75419},
  'february': {'total_card_swiped': 67491},
  'march': {'total_card_swiped': 79897},
  'april': {'total_card_swiped': 70603}},
 '167TH ST-GRAND CONCOURSE      ': {'january': {'total_card_swiped': 103877},
  'february': {'total_card_swiped': 89788},
  'march': {'total_card_swiped': 95536},
  'april': {'total_card_swiped': 92091}},
 '14TH STREET & 7TH AVENUE      ': {'january': {'total_card_swiped': 195036},
  'february': {'total_card_swiped': 203568},
  'march': {'total_card_swiped': 201331},
  'april': {'total_card_swiped': 207877}},
 'CASTLE HILL AVENUE            ': {'january': {'total_card_swiped': 76299},
  'february': {'total_card_swiped': 68325},
  'march': {'total_card_swiped': 71460},
  'april': {'total_card_swiped': 67579}},
 'WESTCHESTER SQUARE            ': {'january': {'total_card_swiped': 59221},
  'february': {'total_card_swiped': 53104},
  'march': {'total_card_swiped': 56642},
  'april': {'total_card_swiped': 51542}},
 'BOROUGH HALL - COURT STREET   ': {'january': {'total_card_swiped': 288209},
  'february': {'total_card_swiped': 276338},
  'march': {'total_card_swiped': 286930},
  'april': {'total_card_swiped': 283956}},
 'CHURCH AVENUE & NOSTRAND AV   ': {'january': {'total_card_swiped': 110072},
  'february': {'total_card_swiped': 94437},
  'march': {'total_card_swiped': 101402},
  'april': {'total_card_swiped': 98491}},
 'FLATBUSH AVE & NOSTRAND AV    ': {'january': {'total_card_swiped': 167918},
  'february': {'total_card_swiped': 152421},
  'march': {'total_card_swiped': 165024},
  'april': {'total_card_swiped': 152460}},
 '23RD STREET & 8TH AVENUE      ': {'january': {'total_card_swiped': 192681},
  'february': {'total_card_swiped': 155069},
  'march': {'total_card_swiped': 185270},
  'april': {'total_card_swiped': 189381}},
 'FORDHAM RD/GRAND CONCOURSE    ': {'january': {'total_card_swiped': 119137},
  'february': {'total_card_swiped': 109031},
  'march': {'total_card_swiped': 113396},
  'april': {'total_card_swiped': 110470}},
 'SEVENTH AVENUE & WEST 53RD    ': {'january': {'total_card_swiped': 114013},
  'february': {'total_card_swiped': 111111},
  'march': {'total_card_swiped': 145755},
  'april': {'total_card_swiped': 150379}},
 'PARSONS BLVD & HILLSIDE AV    ': {'january': {'total_card_swiped': 81093},
  'february': {'total_card_swiped': 70978},
  'march': {'total_card_swiped': 76725},
  'april': {'total_card_swiped': 70773}},
 '169TH STREET & HILLSIDE AVE   ': {'january': {'total_card_swiped': 91067},
  'february': {'total_card_swiped': 82127},
  'march': {'total_card_swiped': 87274},

In [58]:
all_21_totals = []
all_22_totals = []

all_21_totals.append(total21_by_months)
all_22_totals.append(total22_by_months)

In [60]:
df1 = pd.DataFrame (all_21_totals)
df1

,WHITEHALL STREET,CYPRESS HILLS,75TH STREET & ELDERTS LANE,85TH STREET & FOREST PKWAY,WOODHAVEN BOULEVARD,104TH STREET,111TH STREET,121ST STREET,42ND STREET & 8TH AVENUE,34TH STREET & 8TH AVENUE,...,SBS-M86 @ LIVINGSTON PLAZA,MTABC - EASTCHESTER 2,SBS-B46 @ LIVINGSTON PLAZA,SBS-Q44 @ LIVINGSTON PLAZA,SBS-M23 @ LIVINGSTON PLAZA,SBS-M79 @ LIVINGSTON PLAZA,SBS-BX6 @ LIVINGSTON PLAZA,SBS-Q52/53 @ LIVINGSTON PLAZA,SBS-B82 @ LIVINGSTON PLAZA,SBS-M14 @ LIVINGSTON PLAZA
0,"{'january': {'total_card_swiped': 109512}, 'fe...","{'january': {'total_card_swiped': 17025}, 'feb...","{'january': {'total_card_swiped': 40688}, 'feb...","{'january': {'total_card_swiped': 43753}, 'feb...","{'january': {'total_card_swiped': 48442}, 'feb...","{'january': {'total_card_swiped': 30421}, 'feb...","{'january': {'total_card_swiped': 23468}, 'feb...","{'january': {'total_card_swiped': 24368}, 'feb...","{'january': {'total_card_swiped': 581070}, 'fe...","{'january': {'total_card_swiped': 410914}, 'fe...",...,"{'january': {'total_card_swiped': 0.0}, 'febru...","{'january': {'total_card_swiped': 0.0}, 'febru...","{'january': {'total_card_swiped': 0.0}, 'febru...","{'january': {'total_card_swiped': 0.0}, 'febru...","{'january': {'total_card_swiped': 0.0}, 'febru...","{'january': {'total_card_swiped': 0.0}, 'febru...","{'january': {'total_card_swiped': 0.0}, 'febru...","{'january': {'total_card_swiped': 0.0}, 'febru...","{'january': {'total_card_swiped': 0.0}, 'febru...","{'january': {'total_card_swiped': 0.0}, 'febru..."

In [69]:
df1.to_csv ("2021_swipescrape.csv", index= False, encoding = "UTF-8")

In [71]:
df2 = pd.DataFrame (all_22_totals)
df2

,WHITEHALL STREET,CYPRESS HILLS,75TH STREET & ELDERTS LANE,85TH STREET & FOREST PKWAY,WOODHAVEN BOULEVARD,104TH STREET,111TH STREET,121ST STREET,42ND STREET & 8TH AVENUE,34TH STREET & 8TH AVENUE,...,MTABC - EASTCHESTER 2,SBS-B46 @ LIVINGSTON PLAZA,SBS-Q44 @ LIVINGSTON PLAZA,SBS-BX6 @ LIVINGSTON PLAZA,SBS-Q52/53 @ LIVINGSTON PLAZA,SBS-B82 @ LIVINGSTON PLAZA,SBS-M14 @ LIVINGSTON PLAZA,SBS-M23 @ LIVINGSTON PLAZA,SBS-M79 @ LIVINGSTON PLAZA,CLARK STREET-HENRY STREET
0,"{'january': {'total_card_swiped': 175529}, 'fe...","{'january': {'total_card_swiped': 18595}, 'feb...","{'january': {'total_card_swiped': 53080}, 'feb...","{'january': {'total_card_swiped': 52242}, 'feb...","{'january': {'total_card_swiped': 53070}, 'feb...","{'january': {'total_card_swiped': 37951}, 'feb...","{'january': {'total_card_swiped': 30586}, 'feb...","{'january': {'total_card_swiped': 26389}, 'feb...","{'january': {'total_card_swiped': 891179}, 'fe...","{'january': {'total_card_swiped': 595660}, 'fe...",...,"{'january': {'total_card_swiped': 125}, 'febru...","{'january': {'total_card_swiped': 136}, 'febru...","{'january': {'total_card_swiped': 292}, 'febru...","{'january': {'total_card_swiped': 146}, 'febru...","{'january': {'total_card_swiped': 213}, 'febru...","{'january': {'total_card_swiped': 96}, 'februa...","{'january': {'total_card_swiped': 107}, 'febru...","{'january': {'total_card_swiped': 35}, 'februa...","{'january': {'total_card_swiped': 20}, 'februa...","{'january': {'total_card_swiped': 0.0}, 'febru..."

In [73]:
df2.to_csv ("2022_swipescrape.csv", index= False, encoding = "UTF-8")